// Auto-generated by tools/extract-questions.js — do not edit manually
// Generated: 2026-04-27
const GAME_QUESTIONS = {
  "g1-l1": {
    "label": "중1 L1 · be동사 & 일반동사",
    "color": "#0ea5e9",
    "questions": [
      {
        "id": "g1_l1_a1",
        "kor": "그는 나의 선생님이다.",
        "eng": "He ___ my teacher.",
        "ans": "is",
        "opts": [
          "am",
          "is",
          "are",
          "was"
        ]
      },
      {
        "id": "g1_l1_a2",
        "kor": "그들은 나의 이웃이다.",
        "eng": "They ___ my neighbors.",
        "ans": "are",
        "opts": [
          "is",
          "are",
          "am",
          "be"
        ]
      },
      {
        "id": "g1_l1_a3",
        "kor": "우리는 도서관에 있다.",
        "eng": "We ___ in the library.",
        "ans": "are",
        "opts": [
          "am",
          "is",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l1_a4",
        "kor": "나는 키가 140cm이다.",
        "eng": "I ___ 140 cm tall.",
        "ans": "am",
        "opts": [
          "is",
          "am",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l1_a5",
        "kor": "그 영화는 재미있다.",
        "eng": "The movie ___ funny.",
        "ans": "is",
        "opts": [
          "am",
          "are",
          "is",
          "be"
        ]
      },
      {
        "id": "g1_l1_a6",
        "kor": "너는 학교에 지각이다.",
        "eng": "You ___ late for school.",
        "ans": "are",
        "opts": [
          "am",
          "is",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l1_a7",
        "kor": "Irene과 Jim은 같은 반이다.",
        "eng": "Irene and Jim ___ in the same class.",
        "ans": "are",
        "opts": [
          "is",
          "am",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l1_a8",
        "kor": "이 재킷은 비싸지 않다. 나는 그것을 쉽게 살 수 있다.",
        "eng": "This jacket ___ expensive. I can buy it easily.",
        "ans": "is not",
        "opts": [
          "is not",
          "are not",
          "not is",
          "am not"
        ]
      },
      {
        "id": "g1_l1_a9",
        "kor": "지금 화창하지 않다. 흐리고 비가 온다.",
        "eng": "It ___ sunny now. It is cloudy and rainy.",
        "ans": "is not",
        "opts": [
          "is not",
          "are not",
          "not is",
          "be not"
        ]
      },
      {
        "id": "g1_l1_a10",
        "kor": "나의 부모님은 의사가 아니다. 그들은 선생님이다.",
        "eng": "My parents ___ doctors. They are teachers. (be, 부정형)",
        "ans": "are not",
        "opts": [
          "is not",
          "are not",
          "not are",
          "be not"
        ]
      },
      {
        "id": "g1_l1_b1",
        "kor": "나는 여자 형제가 둘 있다. 우리는 서로 닮았다.",
        "eng": "I ___ two sisters. We resemble each other.",
        "ans": "have",
        "opts": [
          "have",
          "has",
          "having",
          "to have"
        ]
      },
      {
        "id": "g1_l1_b3",
        "kor": "Kevin은 월요일마다 바이올린 수업을 받는다.",
        "eng": "Kevin ___ violin lessons on Mondays.",
        "ans": "takes",
        "opts": [
          "take",
          "takes",
          "taked",
          "taking"
        ]
      },
      {
        "id": "g1_l1_b5",
        "kor": "Judy는 선생님이다. 그녀는 과학을 가르친다.",
        "eng": "Judy is a teacher. She ___ science.",
        "ans": "teaches",
        "opts": [
          "teach",
          "teachs",
          "teaches",
          "teaching"
        ]
      },
      {
        "id": "g1_l1_b9",
        "kor": "Mia는 걸어서 학교에 간다.",
        "eng": "Mia ___ to school on foot.",
        "ans": "goes",
        "opts": [
          "go",
          "goes",
          "gos",
          "going"
        ]
      },
      {
        "id": "g1_l1_b11",
        "kor": "Sophie는 가족과 함께 캠핑을 간다.",
        "eng": "Sophie ___ camping with her family.",
        "ans": "goes",
        "opts": [
          "go",
          "gos",
          "goes",
          "going"
        ]
      },
      {
        "id": "g1_l1_b13",
        "kor": "우리는 매일 영어를 공부한다.",
        "eng": "We ___ English every day.",
        "ans": "study",
        "opts": [
          "study",
          "studies",
          "studys",
          "studying"
        ]
      },
      {
        "id": "g1_l1_b15",
        "kor": "Diego는 Bella의 사진을 온라인에 올린다.",
        "eng": "Diego ___ pictures of Bella online.",
        "ans": "posts",
        "opts": [
          "post",
          "posts",
          "postes",
          "posting"
        ]
      },
      {
        "id": "g1_l1_b17",
        "kor": "Amara는 매일 댄스 동작을 연습한다.",
        "eng": "Amara ___ dance moves every day.",
        "ans": "practices",
        "opts": [
          "practice",
          "practices",
          "practicees",
          "practicing"
        ]
      },
      {
        "id": "g1_l1_b19",
        "kor": "그 아기는 밤에 자주 운다.",
        "eng": "The baby often ___ at night.",
        "ans": "cries",
        "opts": [
          "cry",
          "crys",
          "cries",
          "crying"
        ]
      }
    ]
  },
  "g1-l2": {
    "label": "중1 L2 · 현재진행형 & 동명사",
    "color": "#6366f1",
    "questions": [
      {
        "id": "g1_l2_s0q1",
        "kor": "나는 지금 책을 읽고 있는 중이다.",
        "eng": "I ___ a book right now.",
        "ans": "am reading",
        "opts": [
          "am reading",
          "is reading",
          "are reading",
          "reading"
        ]
      },
      {
        "id": "g1_l2_s0q2",
        "kor": "그녀는 방에서 음악을 듣고 있다.",
        "eng": "She ___ to music in her room.",
        "ans": "is listening",
        "opts": [
          "listening",
          "are listening",
          "am listening",
          "is listening"
        ]
      },
      {
        "id": "g1_l2_s0q3",
        "kor": "그들은 축구를 하는 중이다.",
        "eng": "They ___ soccer.",
        "ans": "are playing",
        "opts": [
          "is playing",
          "are playing",
          "playing",
          "am playing"
        ]
      },
      {
        "id": "g1_l2_s0q4",
        "kor": "봐! 아기가 자고 있어.",
        "eng": "Look! The baby ___.",
        "ans": "is sleeping",
        "opts": [
          "is sleeping",
          "are sleeping",
          "sleeps",
          "sleeping"
        ]
      },
      {
        "id": "g1_l2_s0q5",
        "kor": "우리는 지금 영어를 공부하는 중이다.",
        "eng": "We ___ English now.",
        "ans": "are studying",
        "opts": [
          "is studying",
          "am studying",
          "are studying",
          "studying"
        ]
      },
      {
        "id": "g1_l2_s0q6",
        "kor": "그는 우리를 위해 저녁을 만들고 있다.",
        "eng": "He ___ dinner for us.",
        "ans": "is making",
        "opts": [
          "is makeing",
          "are making",
          "making",
          "is making"
        ]
      },
      {
        "id": "g1_l2_s0q7",
        "kor": "밖에 비가 내리고 있어.",
        "eng": "It ___ outside.",
        "ans": "is raining",
        "opts": [
          "is raining",
          "are raining",
          "raining",
          "rains"
        ]
      },
      {
        "id": "g1_l2_s0q8",
        "kor": "나의 부모님은 TV를 보고 계신다.",
        "eng": "My parents ___ TV.",
        "ans": "are watching",
        "opts": [
          "is watching",
          "are watching",
          "watching",
          "am watching"
        ]
      },
      {
        "id": "g1_l2_s0q9",
        "kor": "너는 지금 무엇을 하고 있니?",
        "eng": "What ___ you doing now?",
        "ans": "are",
        "opts": [
          "am",
          "is",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l2_s0q10",
        "kor": "그 버스가 오고 있다.",
        "eng": "The bus ___ coming.",
        "ans": "is",
        "opts": [
          "am",
          "is",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l2_s1q1",
        "kor": "나는 테니스 치는 것을 즐긴다.",
        "eng": "I enjoy ___ tennis.",
        "ans": "playing",
        "opts": [
          "to play",
          "playing",
          "play",
          "played"
        ]
      },
      {
        "id": "g1_l2_s1q2",
        "kor": "걷는 것은 건강에 좋다.",
        "eng": "___ is good for your health.",
        "ans": "Walking",
        "opts": [
          "Walk",
          "Walks",
          "Walking",
          "Walked"
        ]
      },
      {
        "id": "g1_l2_s1q3",
        "kor": "내 취미는 사진을 찍는 것이다.",
        "eng": "My hobby is ___ pictures.",
        "ans": "taking",
        "opts": [
          "to taking",
          "take",
          "took",
          "taking"
        ]
      },
      {
        "id": "g1_l2_s1q4",
        "kor": "그녀는 숙제하는 것을 끝마쳤다.",
        "eng": "She finished ___ her homework.",
        "ans": "doing",
        "opts": [
          "to do",
          "doing",
          "do",
          "done"
        ]
      },
      {
        "id": "g1_l2_s1q5",
        "kor": "도와주어서 고마워.",
        "eng": "Thank you for ___ me.",
        "ans": "helping",
        "opts": [
          "help",
          "helped",
          "to help",
          "helping"
        ]
      },
      {
        "id": "g1_l2_s1q6",
        "kor": "창문 여는 것을 꺼리시나요?",
        "eng": "Do you mind ___ the window?",
        "ans": "opening",
        "opts": [
          "open",
          "to open",
          "opening",
          "opened"
        ]
      },
      {
        "id": "g1_l2_s1q7",
        "kor": "그는 담배 피우는 것을 포기했다.",
        "eng": "He gave up ___.",
        "ans": "smoking",
        "opts": [
          "smoke",
          "to smoke",
          "smoking",
          "smoked"
        ]
      },
      {
        "id": "g1_l2_s1q8",
        "kor": "외식하는 것 어때?",
        "eng": "How about ___ out?",
        "ans": "eating",
        "opts": [
          "eating",
          "eat",
          "to eat",
          "ate"
        ]
      },
      {
        "id": "g1_l2_s1q9",
        "kor": "실수를 하는 것은 정상이다.",
        "eng": "___ mistakes is normal.",
        "ans": "Making",
        "opts": [
          "Make",
          "Makes",
          "Making",
          "To making"
        ]
      },
      {
        "id": "g1_l2_s1q10",
        "kor": "나는 너를 보기를 고대한다.",
        "eng": "I look forward to ___ you.",
        "ans": "seeing",
        "opts": [
          "see",
          "saw",
          "seeing",
          "seen"
        ]
      }
    ]
  },
  "g1-l3": {
    "label": "중1 L3 · be동사 과거형",
    "color": "#22c55e",
    "questions": [
      {
        "id": "g1_l3_a1",
        "kor": "나는 작년에 열 살이었다.",
        "eng": "I ___ ten years old last year.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "am",
          "is"
        ]
      },
      {
        "id": "g1_l3_a2",
        "kor": "그들은 어제 공원에 있었다.",
        "eng": "They ___ in the park yesterday.",
        "ans": "were",
        "opts": [
          "was",
          "were",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l3_a3",
        "kor": "그녀는 방과 후 피곤했다.",
        "eng": "She ___ tired after school.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "is",
          "be"
        ]
      },
      {
        "id": "g1_l3_a4",
        "kor": "우리는 파티에 늦었다.",
        "eng": "We ___ late for the party.",
        "ans": "were",
        "opts": [
          "was",
          "were",
          "is",
          "am"
        ]
      },
      {
        "id": "g1_l3_a5",
        "kor": "시험은 매우 어려웠다.",
        "eng": "The test ___ very hard.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l3_a6",
        "kor": "Tom과 Jina는 작년에 같은 반이었다.",
        "eng": "Tom and Jina ___ in the same class last year.",
        "ans": "were",
        "opts": [
          "was",
          "were",
          "is",
          "are"
        ]
      },
      {
        "id": "g1_l3_a7",
        "kor": "너는 오늘 아침에 집에 있었다.",
        "eng": "You ___ at home this morning.",
        "ans": "were",
        "opts": [
          "was",
          "were",
          "am",
          "is"
        ]
      },
      {
        "id": "g1_l3_a8",
        "kor": "내 강아지는 어제 아팠다.",
        "eng": "My dog ___ sick yesterday.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l3_a9",
        "kor": "그 책들은 책상 위에 있었다.",
        "eng": "The books ___ on the desk.",
        "ans": "were",
        "opts": [
          "was",
          "were",
          "is",
          "am"
        ]
      },
      {
        "id": "g1_l3_a10",
        "kor": "지난 겨울은 춥고 눈이 많이 왔다.",
        "eng": "It ___ cold and snowy last winter. (be)",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l3_b1",
        "kor": "그는 어제 학교에 없었다. 그는 집에 있었다.",
        "eng": "He ___ at school yesterday. He was at home.",
        "ans": "was not",
        "opts": [
          "was not",
          "were not",
          "not was",
          "is not"
        ]
      },
      {
        "id": "g1_l3_b2",
        "kor": "아이들은 박물관에서 조용하지 않았다.",
        "eng": "The children ___ quiet in the museum.",
        "ans": "were not",
        "opts": [
          "was not",
          "were not",
          "not were",
          "are not"
        ]
      },
      {
        "id": "g1_l3_b3",
        "kor": "날씨가 좋지 않았다. 비가 오고 바람이 불었다.",
        "eng": "The weather ___ nice. It was rainy and windy.",
        "ans": "was not",
        "opts": [
          "was not",
          "were not",
          "is not",
          "are not"
        ]
      },
      {
        "id": "g1_l3_b4",
        "kor": "나는 시험 전에 긴장하지 않았다. 나는 신이 났다!",
        "eng": "I ___ nervous before the test. I was excited!",
        "ans": "was not",
        "opts": [
          "was not",
          "were not",
          "am not",
          "is not"
        ]
      },
      {
        "id": "g1_l3_b5",
        "kor": "너는 오늘 오후에 도서관에 있었니? 응, 있었어.",
        "eng": "___ you at the library this afternoon? Yes, I was.",
        "ans": "Were",
        "opts": [
          "Was",
          "Were",
          "Is",
          "Are"
        ]
      },
      {
        "id": "g1_l3_b6",
        "kor": "그녀는 결과에 만족했니? 아니, 만족하지 않았어.",
        "eng": "___ she happy with the result? No, she wasn't.",
        "ans": "Was",
        "opts": [
          "Was",
          "Were",
          "Is",
          "Are"
        ]
      },
      {
        "id": "g1_l3_b7",
        "kor": "시험이 어려웠니? 아니, 어렵지 않았어.",
        "eng": "___ the test difficult? No, it wasn't.",
        "ans": "Was",
        "opts": [
          "Was",
          "Were",
          "Is",
          "Are"
        ]
      },
      {
        "id": "g1_l3_b8",
        "kor": "그들은 작년에 너의 반 친구였니? 응, 맞아.",
        "eng": "___ they your classmates last year? Yes, they were.",
        "ans": "Were",
        "opts": [
          "Was",
          "Were",
          "Is",
          "Are"
        ]
      },
      {
        "id": "g1_l3_b9",
        "kor": "나의 할아버지는 농부가 아니었다. 그는 의사였다.",
        "eng": "My grandfather ___ a farmer. He was a doctor.",
        "ans": "was not",
        "opts": [
          "was not",
          "were not",
          "is not",
          "are not"
        ]
      },
      {
        "id": "g1_l3_b10",
        "kor": "그 사과들은 신선하지 않았다. 그것들은 매우 오래되었다.",
        "eng": "The apples ___ fresh. They were very old. (be, 부정형)",
        "ans": "were not",
        "opts": [
          "was not",
          "were not",
          "is not",
          "are not"
        ]
      }
    ]
  },
  "g1-l4": {
    "label": "중1 L4 · to부정사 & will/should",
    "color": "#f59e0b",
    "questions": [
      {
        "id": "g1_l4_a1",
        "kor": "Mia는 나와 함께 탁구를 치고 싶어 한다.",
        "eng": "Mia wants ___ table tennis with me.",
        "ans": "to play",
        "opts": [
          "to play",
          "plays",
          "playing",
          "play"
        ]
      },
      {
        "id": "g1_l4_a2",
        "kor": "그들은 제주도로 여행 가기로 결정했다.",
        "eng": "They decided ___ to Jeju Island.",
        "ans": "to travel",
        "opts": [
          "traveling",
          "travels",
          "to travel",
          "travel"
        ]
      },
      {
        "id": "g1_l4_a3",
        "kor": "Sam은 매일 아침 버스에서 음악 듣는 것을 즐긴다.",
        "eng": "Sam enjoys ___ music on the bus every morning.",
        "ans": "listening",
        "opts": [
          "listening",
          "to listen",
          "listens",
          "listened"
        ]
      },
      {
        "id": "g1_l4_a4",
        "kor": "나는 오늘 밤에 내 프로젝트를 끝내야 한다.",
        "eng": "I need ___ my project tonight.",
        "ans": "to finish",
        "opts": [
          "finish",
          "to finish",
          "finishing",
          "finishes"
        ]
      },
      {
        "id": "g1_l4_a5",
        "kor": "Jake는 점심 후 과학 보고서 작성을 다 마쳤다.",
        "eng": "Jake finished ___ his science report after lunch.",
        "ans": "doing",
        "opts": [
          "doing",
          "to do",
          "does",
          "done"
        ]
      },
      {
        "id": "g1_l4_a6",
        "kor": "우리는 버스 정류장에서 만나기로 합의했다.",
        "eng": "We agreed ___ at the bus stop.",
        "ans": "to meet",
        "opts": [
          "meets",
          "meeting",
          "to meet",
          "meet"
        ]
      },
      {
        "id": "g1_l4_a7",
        "kor": "Tom은 그의 방을 깨끗하게 유지하기로 약속했다.",
        "eng": "Tom promised ___ his room clean.",
        "ans": "to keep",
        "opts": [
          "keeping",
          "to keep",
          "keeps",
          "kept"
        ]
      },
      {
        "id": "g1_l4_a8",
        "kor": "그녀는 모든 시험에서 계속 같은 실수를 했다.",
        "eng": "She kept ___ the same mistake on every test.",
        "ans": "making",
        "opts": [
          "making",
          "to make",
          "made",
          "makes"
        ]
      },
      {
        "id": "g1_l4_a9",
        "kor": "내 여동생은 지난 여름에 자전거 타는 법을 배웠다.",
        "eng": "My sister learned ___ a bike last summer.",
        "ans": "to ride",
        "opts": [
          "riding",
          "rides",
          "to ride",
          "rode"
        ]
      },
      {
        "id": "g1_l4_a10",
        "kor": "너는 금요일까지 양식을 제출해야 한다.",
        "eng": "You need ___ the form by Friday. (to부정사)",
        "ans": "to submit",
        "opts": [
          "submit",
          "submits",
          "submitting",
          "to submit"
        ]
      },
      {
        "id": "g1_l4_b1",
        "kor": "너는 매일 에너지를 절약해야 한다.",
        "eng": "You ___ energy every day.",
        "ans": "should save",
        "opts": [
          "should saves",
          "save should",
          "should save",
          "saves should"
        ]
      },
      {
        "id": "g1_l4_b2",
        "kor": "그녀는 내일 반 앞에서 발표를 할 것이다.",
        "eng": "She ___ a presentation in front of the class tomorrow.",
        "ans": "will do",
        "opts": [
          "wills do",
          "do will",
          "will do",
          "will does"
        ]
      },
      {
        "id": "g1_l4_b3",
        "kor": "제가 오후 3시까지 거기에 도착해야 하나요?",
        "eng": "___ arrive there by 3 p.m.?",
        "ans": "Should I",
        "opts": [
          "I should",
          "Should I",
          "Do I should",
          "Am I should"
        ]
      },
      {
        "id": "g1_l4_b4",
        "kor": "너는 지금 당장 책상을 정리할래?",
        "eng": "___ clean up your desk right now?",
        "ans": "Will you",
        "opts": [
          "Do you will",
          "You will",
          "Will you",
          "Are you will"
        ]
      },
      {
        "id": "g1_l4_b5",
        "kor": "우리는 오늘 오후에 공원에 가지 않을 것이다.",
        "eng": "We ___ go to the park this afternoon.",
        "ans": "will not",
        "opts": [
          "not will",
          "don't will",
          "will not",
          "won't not"
        ]
      },
      {
        "id": "g1_l4_b6",
        "kor": "이번 주말은 따뜻하고 화창할 것이다.",
        "eng": "It ___ warm and sunny this weekend.",
        "ans": "will be",
        "opts": [
          "wills be",
          "will is",
          "will be",
          "is will"
        ]
      },
      {
        "id": "g1_l4_b7",
        "kor": "너는 자전거를 탈 때 헬멧을 써야 한다.",
        "eng": "You ___ wear a helmet when you ride a bike.",
        "ans": "should",
        "opts": [
          "shoulds",
          "should to",
          "are should",
          "should"
        ]
      },
      {
        "id": "g1_l4_b8",
        "kor": "Ben은 저녁 식사 전에 사탕을 먹으면 안 된다.",
        "eng": "Ben ___ eat candy before dinner.",
        "ans": "should not",
        "opts": [
          "not should",
          "doesn't should",
          "should not",
          "should not to"
        ]
      },
      {
        "id": "g1_l4_b9",
        "kor": "우리 지금 떠나야 하나요? 네, 그래야 해요.",
        "eng": "___ we leave now? Yes, we should.",
        "ans": "Should",
        "opts": [
          "Do",
          "Are",
          "Will",
          "Should"
        ]
      },
      {
        "id": "g1_l4_b10",
        "kor": "내가 오늘 밤에 너에게 전화할게.",
        "eng": "I ___ call you later tonight. (will)",
        "ans": "will",
        "opts": [
          "am will",
          "will to",
          "do will",
          "will"
        ]
      }
    ]
  },
  "g1-l5": {
    "label": "중1 L5 · 재귀대명사 & to부정사",
    "color": "#8b5cf6",
    "questions": [
      {
        "id": "g1_l5_a1",
        "kor": "Sarah는 자기 자신을 위해 새 가방을 샀다.",
        "eng": "Sarah bought a new bag for ___.",
        "ans": "herself",
        "opts": [
          "her",
          "herself",
          "hers",
          "she"
        ]
      },
      {
        "id": "g1_l5_a2",
        "kor": "나는 지난 주말 하이킹 중에 다쳤다.",
        "eng": "I hurt ___ while hiking last weekend.",
        "ans": "myself",
        "opts": [
          "me",
          "my",
          "myself",
          "mine"
        ]
      },
      {
        "id": "g1_l5_a3",
        "kor": "우리는 매일 우리 자신을 믿는다.",
        "eng": "We believe in ___ every day.",
        "ans": "ourselves",
        "opts": [
          "us",
          "our",
          "ourself",
          "ourselves"
        ]
      },
      {
        "id": "g1_l5_a4",
        "kor": "남학생들, 반 친구들에게 자기소개를 해 주세요.",
        "eng": "Boys, please introduce ___ to the class.",
        "ans": "yourselves",
        "opts": [
          "yourself",
          "yourselves",
          "yours",
          "yourselve"
        ]
      },
      {
        "id": "g1_l5_a5",
        "kor": "고양이가 거울에서 자기 자신을 본다.",
        "eng": "The cat sees ___ in the mirror.",
        "ans": "itself",
        "opts": [
          "it",
          "its",
          "itself",
          "itselves"
        ]
      },
      {
        "id": "g1_l5_a6",
        "kor": "학생들이 직접 부서진 의자를 고쳤다.",
        "eng": "The students fixed the broken chairs by ___.",
        "ans": "themselves",
        "opts": [
          "themself",
          "themselves",
          "they",
          "theirs"
        ]
      },
      {
        "id": "g1_l5_a7",
        "kor": "내 남동생은 어제 뉴스에서 자신을 보았다.",
        "eng": "My brother saw ___ on the news yesterday.",
        "ans": "himself",
        "opts": [
          "him",
          "himself",
          "his",
          "he"
        ]
      },
      {
        "id": "g1_l5_a8",
        "kor": "나에게 네 자신에 대해 말해 줘, Mia.",
        "eng": "Tell me about ___, Mia.",
        "ans": "yourself",
        "opts": [
          "you",
          "your",
          "yourself",
          "yourselves"
        ]
      },
      {
        "id": "g1_l5_a9",
        "kor": "로봇이 스스로 전원을 껐다.",
        "eng": "The robot turned ___ off.",
        "ans": "itself",
        "opts": [
          "it",
          "its",
          "itself",
          "themself"
        ]
      },
      {
        "id": "g1_l5_a10",
        "kor": "아이들은 놀고 나서 스스로 몸을 씻었다.",
        "eng": "The children washed ___ after playing.",
        "ans": "themselves",
        "opts": [
          "them",
          "themself",
          "themselves",
          "their"
        ]
      },
      {
        "id": "g1_l5_b1",
        "kor": "유나는 책을 읽으러 도서관에 갔다.",
        "eng": "Yuna went to the library ___ a book.",
        "ans": "to read",
        "opts": [
          "read",
          "to read",
          "reading",
          "reads"
        ]
      },
      {
        "id": "g1_l5_b2",
        "kor": "에밀리는 그림용 태블릿을 사기 위해 아르바이트를 했다.",
        "eng": "Emily worked part-time ___ a tablet for drawing.",
        "ans": "to buy",
        "opts": [
          "buy",
          "bought",
          "to buy",
          "buys"
        ]
      },
      {
        "id": "g1_l5_b3",
        "kor": "",
        "eng": "목적('~하기 위해')의 to부정사가 쓰인 문장을 고르시오.",
        "ans": "He studied hard to pass the exam.",
        "opts": [
          "I want to visit Paris.",
          "She plans to become a nurse.",
          "He studied hard to pass the exam.",
          "We decided to move to Busan."
        ]
      },
      {
        "id": "g1_l5_b4",
        "kor": "Noah는 결석을 설명하기 위해 선생님께 문자를 보냈다.",
        "eng": "Noah texted his teacher ___ his absence.",
        "ans": "to explain",
        "opts": [
          "explain",
          "explained",
          "to explain",
          "explaining"
        ]
      },
      {
        "id": "g1_l5_b5",
        "kor": "그녀는 대회에서 이기기 위해 매일 연습했다.",
        "eng": "She practiced every day ___ the contest.",
        "ans": "to win",
        "opts": [
          "win",
          "to win",
          "winning",
          "wins"
        ]
      },
      {
        "id": "g1_l5_b6",
        "kor": "",
        "eng": "다음 문장의 올바른 해석을 고르시오.She went to the market to buy vegetables.",
        "ans": "그녀는 채소를 사기 위해 시장에 갔다.",
        "opts": [
          "그녀는 채소를 사는 것을 좋아해서 시장에 갔다.",
          "그녀는 채소를 사기 위해 시장에 갔다.",
          "그녀는 시장에 가서 채소를 사기로 결정했다.",
          "그녀는 채소를 팔기 위해 시장에 갔다."
        ]
      },
      {
        "id": "g1_l5_b7",
        "kor": "그들은 교통체증을 피하기 위해 일찍 출발했다.",
        "eng": "They left early ___ the traffic.",
        "ans": "to avoid",
        "opts": [
          "avoid",
          "to avoid",
          "avoiding",
          "avoids"
        ]
      },
      {
        "id": "g1_l5_b8",
        "kor": "엄마는 우리 모두를 위해 저녁을 요리하셨다.",
        "eng": "Mom cooked dinner ___ us all.",
        "ans": "to feed",
        "opts": [
          "feed",
          "to feed",
          "feeding",
          "feeds"
        ]
      },
      {
        "id": "g1_l5_b9",
        "kor": "",
        "eng": "밑줄 친 to부정사가 '목적(~하기 위해)'으로 쓰인 것을 고르시오.",
        "ans": "They turned off the lights to save power.",
        "opts": [
          "I need to sleep more.",
          "She plans to travel to Japan.",
          "They turned off the lights to save power.",
          "Tom promised to be on time."
        ]
      },
      {
        "id": "g1_l5_b10",
        "kor": "나는 새로운 단어를 배우기 위해 이 앱을 사용한다.",
        "eng": "I use this app ___ new words. (to부정사)",
        "ans": "to learn",
        "opts": [
          "learn",
          "learned",
          "learning",
          "to learn"
        ]
      }
    ]
  },
  "g1-l6": {
    "label": "중1 L6 · 감각동사 & because",
    "color": "#ef4444",
    "questions": [
      {
        "id": "g1_l6_a1",
        "kor": "새 놀이터는 매우 안전해 보인다.",
        "eng": "The new playground looks very ___.",
        "ans": "safe",
        "opts": [
          "safely",
          "safe",
          "safety",
          "safeness"
        ]
      },
      {
        "id": "g1_l6_a2",
        "kor": "Jake의 그림은 창의적으로 보인다.",
        "eng": "Jake's drawing looks ___.",
        "ans": "creative",
        "opts": [
          "creative",
          "creatively",
          "creation",
          "creating"
        ]
      },
      {
        "id": "g1_l6_a3",
        "kor": "학교 뒤편의 작은 정원은 사랑스러워 보인다.",
        "eng": "The small garden behind the school looks ___.",
        "ans": "lovely",
        "opts": [
          "love",
          "lovingly",
          "lovely",
          "loveliness"
        ]
      },
      {
        "id": "g1_l6_a4",
        "kor": "내 남동생은 경기 전에 매우 긴장해 보인다.",
        "eng": "My brother looks very ___ before the game.",
        "ans": "nervous",
        "opts": [
          "nervous",
          "nervously",
          "nervousness",
          "nerve"
        ]
      },
      {
        "id": "g1_l6_a5",
        "kor": "거리 시장은 주말에 매우 활기차 보인다.",
        "eng": "The street market looks very ___ on weekends.",
        "ans": "lively",
        "opts": [
          "lively",
          "livelily",
          "live",
          "livelihood"
        ]
      },
      {
        "id": "g1_l6_a6",
        "kor": "축제의 라이브 음악은 정말 멋지게 들린다.",
        "eng": "The live music at the festival sounds ___.",
        "ans": "amazing",
        "opts": [
          "amazing",
          "amazingly",
          "amaze",
          "amazed"
        ]
      },
      {
        "id": "g1_l6_a7",
        "kor": "바구니 안의 아기 고양이들은 사랑스러워 보인다.",
        "eng": "The kittens in the basket look ___.",
        "ans": "adorable",
        "opts": [
          "adorable",
          "adorably",
          "adore",
          "adoration"
        ]
      },
      {
        "id": "g1_l6_a8",
        "kor": "새 코치는 모두에게 매우 친절해 보인다.",
        "eng": "The new coach looks very ___ to everyone.",
        "ans": "friendly",
        "opts": [
          "friendlily",
          "friendship",
          "friend",
          "friendly"
        ]
      },
      {
        "id": "g1_l6_a9",
        "kor": "마당의 장미는 훌륭한 향기가 난다.",
        "eng": "The roses in the yard smell ___.",
        "ans": "wonderful",
        "opts": [
          "wonderful",
          "wonderfully",
          "wonder",
          "wondering"
        ]
      },
      {
        "id": "g1_l6_a10",
        "kor": "이 레몬 사탕은 매우 새콤한 맛이 난다.",
        "eng": "This lemon candy tastes very ___.",
        "ans": "sour",
        "opts": [
          "sour",
          "sourly",
          "sourness",
          "souring"
        ]
      },
      {
        "id": "g1_l6_b1",
        "kor": "우리는 집 안에 머물렀다.",
        "eng": "We stayed inside ___.",
        "ans": "because it was raining heavily",
        "opts": [
          "because the weather was nice",
          "because it was raining heavily",
          "because we wanted to go out",
          "because the sun was bright"
        ]
      },
      {
        "id": "g1_l6_b3",
        "kor": "그녀는 스쿨버스를 놓쳤다.",
        "eng": "___, she missed the school bus.",
        "ans": "Because she got up late",
        "opts": [
          "Because she left home early",
          "Because she got up late",
          "Because she was on time",
          "Because she ran fast"
        ]
      },
      {
        "id": "g1_l6_b4",
        "kor": "Tom은 TV를 껐다.",
        "eng": "Tom turned off the TV ___.",
        "ans": "because he needed to study",
        "opts": [
          "because he wanted to watch more",
          "because it was his favorite show",
          "because he needed to study",
          "because the show was interesting"
        ]
      },
      {
        "id": "g1_l6_b5",
        "kor": "우리는 소풍을 갈 수 없었다.",
        "eng": "___, we couldn't go on the picnic.",
        "ans": "Because there was a big storm",
        "opts": [
          "Because the weather was sunny",
          "Because everyone wanted to go",
          "Because we had enough food",
          "Because there was a big storm"
        ]
      },
      {
        "id": "g1_l6_b6",
        "kor": "Leo는 내 우산을 빌렸다.",
        "eng": "Leo borrowed my umbrella ___.",
        "ans": "because he forgot his own",
        "opts": [
          "because it was a hot day",
          "because he forgot his own",
          "because he had one already",
          "because it wasn't raining"
        ]
      },
      {
        "id": "g1_l6_b7",
        "kor": "Amy는 시험에서 만점을 받았다.",
        "eng": "Amy got a perfect score on the test ___.",
        "ans": "because she reviewed her notes every day",
        "opts": [
          "because she didn't study at all",
          "because she played all day",
          "because she reviewed her notes every day",
          "because she forgot the material"
        ]
      },
      {
        "id": "g1_l6_b8",
        "kor": "우리는 의자를 추가로 주문했다.",
        "eng": "___, we ordered extra chairs.",
        "ans": "Because we were expecting many visitors",
        "opts": [
          "Because there were enough seats",
          "Because only a few guests came",
          "Because we were expecting many visitors",
          "Because the room was empty"
        ]
      },
      {
        "id": "g1_l6_b9",
        "kor": "Sam은 선크림을 발랐다.",
        "eng": "Sam put on sunscreen ___.",
        "ans": "because the sun was very strong",
        "opts": [
          "because it was a cloudy day",
          "because the sun was very strong",
          "because he didn't like the beach",
          "because he wanted to stay inside"
        ]
      },
      {
        "id": "g1_l6_b10",
        "kor": "Nora는 일찍 잠자리에 들었다.",
        "eng": "Nora went to bed early ___.",
        "ans": "because she had an early practice the next day",
        "opts": [
          "because she wasn't tired",
          "because she wanted to stay up late",
          "because she had an early practice the next day",
          "because she finished homework late"
        ]
      }
    ]
  },
  "g2-l1": {
    "label": "중2 L1 · 수여동사 & 관계대명사",
    "color": "#0d9488",
    "questions": [
      {
        "id": "g2_l1_a1",
        "kor": "그녀는 경기 후 나에게 따뜻한 포옹을 해 주었다.",
        "eng": "She gave ___ a warm hug after the game.",
        "ans": "me",
        "opts": [
          "I",
          "me",
          "my",
          "mine"
        ]
      },
      {
        "id": "g2_l1_a2",
        "kor": "아빠는 자기 전에 우리에게 재미있는 이야기를 해 주셨다.",
        "eng": "My dad told ___ a funny story before bed.",
        "ans": "us",
        "opts": [
          "we",
          "our",
          "us",
          "ours"
        ]
      },
      {
        "id": "g2_l1_a3",
        "kor": "Jake는 그들에게 자신의 새 로봇 모델을 보여주었다.",
        "eng": "Jake showed ___ his new robot model.",
        "ans": "them",
        "opts": [
          "they",
          "their",
          "theirs",
          "them"
        ]
      },
      {
        "id": "g2_l1_a4",
        "kor": "할머니가 그에게 새 겨울 코트를 사 주셨다.",
        "eng": "Grandma bought ___ a new winter coat.",
        "ans": "him",
        "opts": [
          "he",
          "his",
          "him",
          "himself"
        ]
      },
      {
        "id": "g2_l1_a5",
        "kor": "사서가 그녀에게 천문학 책 세 권을 빌려주었다.",
        "eng": "The librarian lent ___ three books on astronomy.",
        "ans": "her",
        "opts": [
          "she",
          "her",
          "hers",
          "herself"
        ]
      },
      {
        "id": "g2_l1_a6",
        "kor": "그녀는 방과 후 그에게 새 노트를 주었다.",
        "eng": "She gave a new notebook ___ him after school.",
        "ans": "to",
        "opts": [
          "to",
          "for",
          "of",
          "at"
        ]
      },
      {
        "id": "g2_l1_a7",
        "kor": "할아버지가 우리에게 나무 새집을 만들어 주셨다.",
        "eng": "Grandpa made a wooden birdhouse ___ us.",
        "ans": "for",
        "opts": [
          "to",
          "for",
          "in",
          "on"
        ]
      },
      {
        "id": "g2_l1_a8",
        "kor": "언니가 나에게 귀여운 스카프를 사 주었다.",
        "eng": "My sister bought a cute scarf ___ me.",
        "ans": "for",
        "opts": [
          "to",
          "for",
          "of",
          "with"
        ]
      },
      {
        "id": "g2_l1_b1",
        "kor": "나는 바이올린을 정말 잘 연주하는 사촌이 있다.",
        "eng": "I have a cousin ___ plays the violin really well.",
        "ans": "who",
        "opts": [
          "who",
          "which",
          "what",
          "whom"
        ]
      },
      {
        "id": "g2_l1_b2",
        "kor": "우리는 혼자서 집을 청소할 수 있는 로봇을 가지고 있다.",
        "eng": "We have a robot ___ can clean the house by itself.",
        "ans": "that",
        "opts": [
          "who",
          "that",
          "whom",
          "what"
        ]
      },
      {
        "id": "g2_l1_b3",
        "kor": "그녀는 어린이 병원에서 일하는 간호사이다.",
        "eng": "She is a nurse ___ works at the children's hospital.",
        "ans": "who",
        "opts": [
          "which",
          "what",
          "who",
          "whom"
        ]
      },
      {
        "id": "g2_l1_b4",
        "kor": "그는 차 밑에 숨어 있던 길고양이를 발견했다.",
        "eng": "He found a stray cat ___ was hiding under the car.",
        "ans": "which",
        "opts": [
          "who",
          "which",
          "whom",
          "what"
        ]
      },
      {
        "id": "g2_l1_b5",
        "kor": "Leo는 항상 수업에 일찍 오는 학생이다.",
        "eng": "Leo is a student ___ always arrives early to class.",
        "ans": "who",
        "opts": [
          "who",
          "which",
          "what",
          "whom"
        ]
      },
      {
        "id": "g2_l1_b6",
        "kor": "그녀는 먼 행성을 배경으로 한 책을 읽었다.",
        "eng": "She read a book ___ was set on a distant planet.",
        "ans": "that",
        "opts": [
          "who",
          "whom",
          "that",
          "what"
        ]
      },
      {
        "id": "g2_l1_b7",
        "kor": "우리 학교에는 허브와 채소를 기르는 정원이 있다.",
        "eng": "My school has a garden ___ grows herbs and vegetables.",
        "ans": "that",
        "opts": [
          "who",
          "whom",
          "what",
          "that"
        ]
      },
      {
        "id": "g2_l1_b8",
        "kor": "Nora는 50개 이상의 단어를 말할 수 있는 앵무새를 키우고 있다.",
        "eng": "Nora has a parrot ___ can say over fifty words.",
        "ans": "that",
        "opts": [
          "who",
          "whom",
          "what",
          "that"
        ]
      }
    ]
  },
  "g2-l2": {
    "label": "중2 L2 · 현재완료 & 비교급",
    "color": "#f97316",
    "questions": [
      {
        "id": "g2_l2_a1",
        "kor": "나는 이 영화를 전에 본 적이 있다.",
        "eng": "I ___ seen this film before.",
        "ans": "have",
        "opts": [
          "have",
          "has",
          "had",
          "am"
        ]
      },
      {
        "id": "g2_l2_a2",
        "kor": "그녀는 방금 숙제를 끝냈다.",
        "eng": "She ___ just finished her homework.",
        "ans": "has",
        "opts": [
          "have",
          "has",
          "had",
          "is"
        ]
      },
      {
        "id": "g2_l2_a3",
        "kor": "그들은 10년 동안 여기서 살아 왔다.",
        "eng": "They ___ lived here for ten years.",
        "ans": "have",
        "opts": [
          "have",
          "has",
          "had",
          "are"
        ]
      },
      {
        "id": "g2_l2_a4",
        "kor": "우리 아빠는 이미 저녁을 드셨다.",
        "eng": "My dad ___ already eaten dinner.",
        "ans": "has",
        "opts": [
          "have",
          "has",
          "had",
          "was"
        ]
      },
      {
        "id": "g2_l2_a5",
        "kor": "Jake와 나는 한 번도 초밥을 먹어본 적이 없다.",
        "eng": "Jake and I ___ never tried sushi.",
        "ans": "have",
        "opts": [
          "have",
          "has",
          "had",
          "were"
        ]
      },
      {
        "id": "g2_l2_a6",
        "kor": "Mia는 올해 소설 세 편을 썼다.",
        "eng": "Mia ___ three novels this year.",
        "ans": "has written",
        "opts": [
          "has written",
          "has wrote",
          "have written",
          "is writing"
        ]
      },
      {
        "id": "g2_l2_a7",
        "kor": "우리는 이 노래를 전에 들어본 적이 있다.",
        "eng": "We ___ this song before.",
        "ans": "have heard",
        "opts": [
          "have hear",
          "have heard",
          "has heard",
          "are heard"
        ]
      },
      {
        "id": "g2_l2_a8",
        "kor": "그는 또 휴대폰을 망가뜨렸다.",
        "eng": "He ___ his phone again.",
        "ans": "has broken",
        "opts": [
          "has broke",
          "has broken",
          "have broken",
          "was broken"
        ]
      },
      {
        "id": "g2_l2_a9",
        "kor": "그녀는 어렸을 때부터 기타를 연주해 왔다.",
        "eng": "She ___ the guitar since she was little.",
        "ans": "has played",
        "opts": [
          "has playing",
          "has played",
          "is played",
          "have played"
        ]
      },
      {
        "id": "g2_l2_a17",
        "kor": "Jake는 세 달 동안 한국어를 공부해 왔다.",
        "eng": "Jake has studied Korean ___ three months.",
        "ans": "for",
        "opts": [
          "since",
          "for",
          "in",
          "at"
        ]
      },
      {
        "id": "g2_l2_a18",
        "kor": "그녀는 2021년부터 서울에 살아 왔다.",
        "eng": "She has lived in Seoul ___ 2021.",
        "ans": "since",
        "opts": [
          "since",
          "for",
          "during",
          "from"
        ]
      },
      {
        "id": "g2_l2_a19",
        "kor": "나는 오늘 아침부터 아무것도 먹지 않았다.",
        "eng": "I have not eaten anything ___ this morning.",
        "ans": "since",
        "opts": [
          "for",
          "since",
          "at",
          "in"
        ]
      },
      {
        "id": "g2_l2_a20",
        "kor": "우리는 오랜 세월 동안 절친한 친구로 지내 왔다.",
        "eng": "We have been best friends ___ many years.",
        "ans": "for",
        "opts": [
          "since",
          "for",
          "during",
          "from"
        ]
      },
      {
        "id": "g2_l2_b1",
        "kor": "이 가방이 내 것보다 더 가볍다.",
        "eng": "This bag is ___ (light) than mine.",
        "ans": "lighter",
        "opts": [
          "lighter",
          "more light",
          "lightest",
          "most light"
        ]
      },
      {
        "id": "g2_l2_b2",
        "kor": "나에게는 수학이 영어보다 더 어렵다.",
        "eng": "Math is ___ (difficult) than English for me.",
        "ans": "more difficult",
        "opts": [
          "difficulter",
          "more difficult",
          "most difficult",
          "difficultly"
        ]
      },
      {
        "id": "g2_l2_b3",
        "kor": "그녀는 오빠보다 더 빨리 달린다.",
        "eng": "She runs ___ (fast) than her brother.",
        "ans": "faster",
        "opts": [
          "more fast",
          "faster",
          "fastest",
          "most fast"
        ]
      },
      {
        "id": "g2_l2_b4",
        "kor": "이 소파가 저 의자보다 더 편안하다.",
        "eng": "This sofa is ___ (comfortable) than that chair.",
        "ans": "more comfortable",
        "opts": [
          "comfortabler",
          "more comfortable",
          "most comfortable",
          "comfortablest"
        ]
      },
      {
        "id": "g2_l2_b5",
        "kor": "오늘은 어제보다 더 덥다.",
        "eng": "Today is ___ (hot) than yesterday.",
        "ans": "hotter",
        "opts": [
          "more hot",
          "hotter",
          "hottest",
          "hoter"
        ]
      },
      {
        "id": "g2_l2_b6",
        "kor": "그는 팀에서 가장 키가 큰 선수다.",
        "eng": "He is ___ (tall) player on the team.",
        "ans": "the tallest",
        "opts": [
          "taller",
          "tallest",
          "the tallest",
          "most tallest"
        ]
      },
      {
        "id": "g2_l2_b7",
        "kor": "이것은 가게에서 가장 비싼 시계다.",
        "eng": "This is ___ (expensive) watch in the shop.",
        "ans": "the most expensive",
        "opts": [
          "more expensive",
          "most expensive",
          "the most expensive",
          "expensivest"
        ]
      },
      {
        "id": "g2_l2_b8",
        "kor": "그녀는 우리 반에서 가장 우수한 학생이다.",
        "eng": "She is ___ (good) student in our class.",
        "ans": "the best",
        "opts": [
          "the better",
          "the best",
          "the most good",
          "gooder"
        ]
      }
    ]
  },
  "g2-l3": {
    "label": "중2 L3 · 형용사 to부정사 & if",
    "color": "#ec4899",
    "questions": [
      {
        "id": "g2_l3_a1",
        "kor": "소풍에 먹을 것이 필요하다.",
        "eng": "I need something ___ for the picnic.",
        "ans": "to eat",
        "opts": [
          "eating",
          "to eat",
          "to eating",
          "eaten"
        ]
      },
      {
        "id": "g2_l3_a2",
        "kor": "그녀는 월요일까지 제출해야 할 보고서가 많다.",
        "eng": "She has a lot of reports ___ by Monday.",
        "ans": "to submit",
        "opts": [
          "submitting",
          "to submit",
          "submitted",
          "submit"
        ]
      },
      {
        "id": "g2_l3_a3",
        "kor": "그는 방과 후 공부할 조용한 구석을 찾았다.",
        "eng": "He found a quiet corner ___ after school.",
        "ans": "to study",
        "opts": [
          "study",
          "studied",
          "to study",
          "studying"
        ]
      },
      {
        "id": "g2_l3_a4",
        "kor": "떠나기 전에 발표할 것이 있나요?",
        "eng": "Do you have anything ___ before leaving?",
        "ans": "to announce",
        "opts": [
          "to announce",
          "announcing",
          "announced",
          "announce"
        ]
      },
      {
        "id": "g2_l3_a5",
        "kor": "그들은 도시를 안내해 줄 가이드를 찾고 있다.",
        "eng": "They are looking for a guide ___ them around the city.",
        "ans": "to show",
        "opts": [
          "showing",
          "show",
          "to show",
          "to showing"
        ]
      },
      {
        "id": "g2_l3_a6",
        "kor": "이 공원에는 앉을 벤치가 없다.",
        "eng": "There is no bench ___ in this park.",
        "ans": "to sit on",
        "opts": [
          "to sit",
          "sit on",
          "to sit on",
          "sitting on"
        ]
      },
      {
        "id": "g2_l3_a7",
        "kor": "그는 필기할 펜을 가져왔다.",
        "eng": "He brought a pen ___.",
        "ans": "to write with",
        "opts": [
          "to write",
          "write with",
          "to write with",
          "writing with"
        ]
      },
      {
        "id": "g2_l3_a8",
        "kor": "그녀는 이야기할 주제를 찾고 있다.",
        "eng": "She is looking for a topic ___.",
        "ans": "to talk about",
        "opts": [
          "talk about",
          "talking about",
          "to talk",
          "to talk about"
        ]
      },
      {
        "id": "g2_l3_a9",
        "kor": "그는 하이킹 중 마실 물병을 가져왔다.",
        "eng": "He brought a bottle ___ on the hike.",
        "ans": "to drink from",
        "opts": [
          "to drink",
          "drink from",
          "to drink from",
          "drinking from"
        ]
      },
      {
        "id": "g2_l3_b1",
        "kor": "내일 비가 오면, 우리는 여행을 취소할 것이다.",
        "eng": "If it ___ tomorrow, we will cancel the trip.",
        "ans": "rains",
        "opts": [
          "rains",
          "will rain",
          "rained",
          "is raining"
        ]
      },
      {
        "id": "g2_l3_b2",
        "kor": "도움이 필요하면 그녀가 전화할 것이다.",
        "eng": "She will call you if she ___ any help.",
        "ans": "needs",
        "opts": [
          "needs",
          "will need",
          "needed",
          "is needing"
        ]
      },
      {
        "id": "g2_l3_b4",
        "kor": "이번 주말 날씨가 좋으면, 캠핑 가자.",
        "eng": "If the weather ___ nice this weekend, let's go camping.",
        "ans": "is",
        "opts": [
          "is",
          "will be",
          "was",
          "would be"
        ]
      }
    ]
  },
  "g2-l4": {
    "label": "중2 L4 · so~that & 수동태",
    "color": "#84cc16",
    "questions": [
      {
        "id": "g2_l4_a1",
        "kor": "그는 너무 피곤해서 움직일 수 없었다.",
        "eng": "He was ___ tired that he couldn't move.",
        "ans": "so",
        "opts": [
          "so",
          "very",
          "too",
          "quite"
        ]
      },
      {
        "id": "g2_l4_a2",
        "kor": "그 영화는 너무 지루해서 우리는 일찍 떠났다.",
        "eng": "The movie was ___ boring that we left early.",
        "ans": "so",
        "opts": [
          "too",
          "very",
          "quite",
          "so"
        ]
      },
      {
        "id": "g2_l4_a3",
        "kor": "그 수프는 너무 뜨거워서 그녀는 먹을 수 없었다.",
        "eng": "The soup was so hot ___ she couldn't eat it.",
        "ans": "that",
        "opts": [
          "which",
          "when",
          "because",
          "that"
        ]
      },
      {
        "id": "g2_l4_a4",
        "kor": "Jake는 너무 빠르게 달려서 아무도 그를 잡을 수 없었다.",
        "eng": "Jake ran so quickly ___ nobody could catch him.",
        "ans": "that",
        "opts": [
          "when",
          "but",
          "so",
          "that"
        ]
      },
      {
        "id": "g2_l4_a5",
        "kor": "가방이 너무 무거워서 Mia는 도움을 요청했다.",
        "eng": "The bag was so heavy ___ Mia asked for help.",
        "ans": "that",
        "opts": [
          "because",
          "which",
          "that",
          "but"
        ]
      },
      {
        "id": "g2_l4_a6",
        "kor": "하늘이 너무 어두워서 우리는 아무것도 볼 수 없었다.",
        "eng": "The sky was so dark ___ we couldn't see anything.",
        "ans": "that",
        "opts": [
          "where",
          "since",
          "but",
          "that"
        ]
      },
      {
        "id": "g2_l4_a7",
        "kor": "음식이 너무 맛있어서 모두가 더 먹고 싶어했다.",
        "eng": "The food was so ___ that everyone wanted more.",
        "ans": "delicious",
        "opts": [
          "deliciously",
          "delicious",
          "delight",
          "deliciousness"
        ]
      },
      {
        "id": "g2_l4_a8",
        "kor": "그녀는 너무 아름답게 노래해서 관중이 박수를 쳤다.",
        "eng": "She sang so ___ that the crowd applauded.",
        "ans": "beautifully",
        "opts": [
          "beautiful",
          "beauty",
          "beautifully",
          "beautify"
        ]
      },
      {
        "id": "g2_l4_a9",
        "kor": "시험이 너무 어려워서 많은 학생들이 떨어졌다.",
        "eng": "The test was so ___ that many students failed.",
        "ans": "difficult",
        "opts": [
          "difficultly",
          "difficulty",
          "differ",
          "difficult"
        ]
      },
      {
        "id": "g2_l4_a10",
        "kor": "그는 너무 열심히 연습해서 챔피언이 되었다.",
        "eng": "He practiced so ___ that he became the champion.",
        "ans": "hard",
        "opts": [
          "hardly",
          "hard",
          "hardness",
          "harder"
        ]
      },
      {
        "id": "g2_l4_b1",
        "kor": "창문이 어젯밤 누군가에 의해 깨졌다.",
        "eng": "The window ___ by someone last night.",
        "ans": "was broken",
        "opts": [
          "broken",
          "was broken",
          "breaks",
          "is breaking"
        ]
      },
      {
        "id": "g2_l4_b2",
        "kor": "Jake는 한 시간 만에 낡은 자전거를 고쳤다.",
        "eng": "Jake ___ the old bicycle in an hour.",
        "ans": "fixed",
        "opts": [
          "was fixed",
          "is fixed",
          "fixed",
          "were fixed"
        ]
      },
      {
        "id": "g2_l4_b3",
        "kor": "꽃들은 매년 겨울마다 시원한 곳에 보관된다.",
        "eng": "The flowers ___ in a cool place every winter.",
        "ans": "are kept",
        "opts": [
          "keep",
          "kept",
          "are kept",
          "is kept"
        ]
      },
      {
        "id": "g2_l4_b4",
        "kor": "그 오래된 다리는 약 100년 전에 지어졌다.",
        "eng": "The old bridge ___ about a century ago.",
        "ans": "was built",
        "opts": [
          "build",
          "built",
          "is built",
          "was built"
        ]
      },
      {
        "id": "g2_l4_b5",
        "kor": "어제 경기에서 세 골이 득점되었다.",
        "eng": "Three goals ___ scored in the match yesterday.",
        "ans": "were",
        "opts": [
          "is",
          "was",
          "are",
          "were"
        ]
      },
      {
        "id": "g2_l4_b6",
        "kor": "그 편지는 오늘 아침 Yuna가 썼다.",
        "eng": "The letter ___ written by Yuna this morning.",
        "ans": "was",
        "opts": [
          "are",
          "am",
          "were",
          "was"
        ]
      },
      {
        "id": "g2_l4_b7",
        "kor": "많은 책들이 매년 축제에서 판매된다.",
        "eng": "A lot of books ___ sold at the fair every year.",
        "ans": "are",
        "opts": [
          "was",
          "is",
          "am",
          "are"
        ]
      },
      {
        "id": "g2_l4_b8",
        "kor": "특별한 저녁 식사는 매주 일요일 Jake의 아버지가 요리한다.",
        "eng": "The special dinner ___ cooked by Jake's father on Sundays.",
        "ans": "is",
        "opts": [
          "were",
          "are",
          "am",
          "is"
        ]
      }
    ]
  },
  "all": {
    "label": "전체 랜덤",
    "color": "#64748b",
    "questions": []
  }
};
