// Auto-generated by tools/extract-questions.js — do not edit manually
// Generated: 2026-05-17
const GAME_QUESTIONS = {
  "g1-l1": {
    "label": "중1 L1 · be동사 & 일반동사",
    "color": "#0ea5e9",
    "questions": [
      {
        "id": "g1_l1_be_verb_a1",
        "kor": "그는 나의 선생님이다.",
        "eng": "He ___ my teacher.",
        "ans": "is",
        "opts": [
          "is",
          "am",
          "are",
          "was"
        ]
      },
      {
        "id": "g1_l1_be_verb_a2",
        "kor": "그들은 나의 이웃이다.",
        "eng": "They ___ my neighbors.",
        "ans": "are",
        "opts": [
          "is",
          "am",
          "be",
          "are"
        ]
      },
      {
        "id": "g1_l1_be_verb_a3",
        "kor": "우리는 도서관에 있다.",
        "eng": "We ___ in the library.",
        "ans": "are",
        "opts": [
          "is",
          "be",
          "are",
          "am"
        ]
      },
      {
        "id": "g1_l1_be_verb_a4",
        "kor": "나는 키가 140cm이다.",
        "eng": "I ___ 140 cm tall.",
        "ans": "am",
        "opts": [
          "be",
          "am",
          "is",
          "are"
        ]
      },
      {
        "id": "g1_l1_be_verb_a5",
        "kor": "그 영화는 재미있다.",
        "eng": "The movie ___ funny.",
        "ans": "is",
        "opts": [
          "is",
          "am",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l1_be_verb_a6",
        "kor": "너는 학교에 지각이다.",
        "eng": "You ___ late for school.",
        "ans": "are",
        "opts": [
          "am",
          "is",
          "be",
          "are"
        ]
      },
      {
        "id": "g1_l1_be_verb_a7",
        "kor": "Irene과 Jim은 같은 반이다.",
        "eng": "Irene and Jim ___ in the same class.",
        "ans": "are",
        "opts": [
          "am",
          "be",
          "are",
          "is"
        ]
      },
      {
        "id": "g1_l1_be_verb_a8",
        "kor": "이 재킷은 비싸지 않다. 나는 그것을 쉽게 살 수 있다.",
        "eng": "This jacket ___ expensive. I can buy it easily.",
        "ans": "is not",
        "opts": [
          "am not",
          "is not",
          "are not",
          "not is"
        ]
      },
      {
        "id": "g1_l1_be_verb_a9",
        "kor": "지금 화창하지 않다. 흐리고 비가 온다.",
        "eng": "It ___ sunny now. It is cloudy and rainy.",
        "ans": "is not",
        "opts": [
          "is not",
          "are not",
          "not be",
          "am not"
        ]
      },
      {
        "id": "g1_l1_be_verb_a10",
        "kor": "나의 부모님은 의사가 아니다. 그들은 선생님이다.",
        "eng": "My parents ___ doctors. They are teachers.",
        "ans": "are not",
        "opts": [
          "is not",
          "am not",
          "aren't not",
          "are not"
        ]
      },
      {
        "id": "g1_l1_be_verb_b1",
        "kor": "나는 여자 형제가 둘 있다. 우리는 서로 닮았다.",
        "eng": "I ___ two sisters. We resemble each other.",
        "ans": "have",
        "opts": [
          "having",
          "to have",
          "have",
          "has"
        ]
      },
      {
        "id": "g1_l1_be_verb_b3",
        "kor": "Kevin은 월요일마다 바이올린 수업을 받는다.",
        "eng": "Kevin ___ violin lessons on Mondays.",
        "ans": "takes",
        "opts": [
          "taking",
          "takes",
          "take",
          "took"
        ]
      },
      {
        "id": "g1_l1_be_verb_b5",
        "kor": "Judy는 선생님이다. 그녀는 과학을 가르친다.",
        "eng": "Judy is a teacher. She ___ science.",
        "ans": "teaches",
        "opts": [
          "teaches",
          "teach",
          "taught",
          "teaching"
        ]
      },
      {
        "id": "g1_l1_be_verb_b7",
        "kor": "나의 부모님은 병원에서 일하지 않는다. 그들은 선생님이다.",
        "eng": "My parents ___ for a hospital. They are teachers.",
        "ans": "don't work",
        "opts": [
          "doesn't work",
          "not work",
          "works not",
          "don't work"
        ]
      },
      {
        "id": "g1_l1_be_verb_b9",
        "kor": "Mia는 걸어서 학교에 간다.",
        "eng": "Mia ___ to school on foot.",
        "ans": "goes",
        "opts": [
          "went",
          "going",
          "goes",
          "go"
        ]
      },
      {
        "id": "g1_l1_be_verb_b11",
        "kor": "Sophie는 가족과 함께 캠핑을 간다.",
        "eng": "Sophie ___ camping with her family.",
        "ans": "goes",
        "opts": [
          "going",
          "goes",
          "go",
          "went"
        ]
      },
      {
        "id": "g1_l1_be_verb_b13",
        "kor": "우리는 매일 영어를 공부한다.",
        "eng": "We ___ English every day.",
        "ans": "study",
        "opts": [
          "study",
          "studies",
          "studied",
          "studying"
        ]
      },
      {
        "id": "g1_l1_be_verb_b15",
        "kor": "Diego는 Bella의 사진을 온라인에 올린다.",
        "eng": "Diego ___ pictures of Bella online.",
        "ans": "posts",
        "opts": [
          "post",
          "posted",
          "posting",
          "posts"
        ]
      },
      {
        "id": "g1_l1_be_verb_b17",
        "kor": "Amara는 매일 댄스 동작을 연습한다.",
        "eng": "Amara ___ dance moves every day.",
        "ans": "practices",
        "opts": [
          "practiced",
          "practicing",
          "practices",
          "practice"
        ]
      },
      {
        "id": "g1_l1_be_verb_b19",
        "kor": "그 아기는 밤에 자주 운다.",
        "eng": "The baby often ___ at night.",
        "ans": "cries",
        "opts": [
          "crying",
          "cries",
          "cry",
          "cried"
        ]
      },
      {
        "id": "g1_l1_general_verb_hard_a1",
        "kor": "내 친구들과 나는 매주 토요일 공원에서 농구를 한다.",
        "eng": "My friends and I ___ basketball every Saturday at the park.",
        "ans": "play",
        "opts": [
          "play",
          "plays",
          "playing",
          "played"
        ]
      },
      {
        "id": "g1_l1_general_verb_hard_a2",
        "kor": "Mia와 Jake는 주말에 같은 피아노 학원에 다닌다.",
        "eng": "Mia and Jake ___ to the same piano academy on weekends.",
        "ans": "go",
        "opts": [
          "goes",
          "going",
          "went",
          "go"
        ]
      },
      {
        "id": "g1_l1_general_verb_hard_a3",
        "kor": "내 개는 고양이를 좋아하지 않는다 — 하지만 그녀는 우리 토끼와 노는 것을 좋아한다.",
        "eng": "My dog ___ cats — but she loves playing with our rabbit.",
        "ans": "doesn't like",
        "opts": [
          "doesn't likes",
          "not like",
          "doesn't like",
          "don't like"
        ]
      },
      {
        "id": "g1_l1_general_verb_hard_a4",
        "kor": "Tom과 그의 형은 등교일에는 비디오 게임을 하지 않는다 — 주말에만 한다.",
        "eng": "Tom and his brother ___ video games on school days — only on weekends.",
        "ans": "don't play",
        "opts": [
          "not play",
          "don't play",
          "doesn't play",
          "don't plays"
        ]
      }
    ]
  },
  "g1-l2": {
    "label": "중1 L2 · 현재진행형 & 동명사",
    "color": "#6366f1",
    "questions": [
      {
        "id": "g1_l2_gerund_basic_s0q1",
        "kor": "나는 지금 책을 읽고 있는 중이다.",
        "eng": "I ___ a book right now.",
        "ans": "am reading",
        "opts": [
          "am reading",
          "is reading",
          "are reading",
          "reading"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q2",
        "kor": "그녀는 방에서 음악을 듣고 있다.",
        "eng": "She ___ to music in her room.",
        "ans": "is listening",
        "opts": [
          "listening",
          "are listening",
          "am listening",
          "is listening"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q3",
        "kor": "그들은 축구를 하는 중이다.",
        "eng": "They ___ soccer.",
        "ans": "are playing",
        "opts": [
          "playing",
          "plays",
          "are playing",
          "is playing"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q4",
        "kor": "봐! 아기가 자고 있어.",
        "eng": "Look! The baby ___.",
        "ans": "is sleeping",
        "opts": [
          "sleeping",
          "is sleeping",
          "are sleeping",
          "sleeps"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q5",
        "kor": "우리는 지금 영어를 공부하는 중이다.",
        "eng": "We ___ English now.",
        "ans": "are studying",
        "opts": [
          "are studying",
          "is studying",
          "studies",
          "studying"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q6",
        "kor": "그는 우리를 위해 저녁을 만들고 있다.",
        "eng": "He ___ dinner for us.",
        "ans": "is making",
        "opts": [
          "is makeing",
          "are making",
          "making",
          "is making"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q7",
        "kor": "밖에 비가 내리고 있어.",
        "eng": "It ___ outside.",
        "ans": "is raining",
        "opts": [
          "raining",
          "rains",
          "is raining",
          "are raining"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q8",
        "kor": "나의 부모님은 TV를 보고 계신다.",
        "eng": "My parents ___ TV.",
        "ans": "are watching",
        "opts": [
          "watch",
          "are watching",
          "is watching",
          "watching"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q9",
        "kor": "너는 지금 무엇을 하고 있니?",
        "eng": "What ___ you doing now?",
        "ans": "are",
        "opts": [
          "are",
          "am",
          "is",
          "be"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q10",
        "kor": "그 버스가 오고 있다.",
        "eng": "The bus ___ coming.",
        "ans": "is",
        "opts": [
          "am",
          "are",
          "be",
          "is"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q1",
        "kor": "나는 테니스 치는 것을 즐긴다.",
        "eng": "I enjoy ___ tennis.",
        "ans": "playing",
        "opts": [
          "play",
          "played",
          "playing",
          "to play"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q2",
        "kor": "걷는 것은 건강에 좋다.",
        "eng": "___ is good for your health.",
        "ans": "Walking",
        "opts": [
          "Walked",
          "Walking",
          "Walk",
          "Walks"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q3",
        "kor": "내 취미는 사진을 찍는 것이다.",
        "eng": "My hobby is ___ pictures.",
        "ans": "taking",
        "opts": [
          "taking",
          "to taking",
          "take",
          "took"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q4",
        "kor": "그녀는 숙제하는 것을 끝마쳤다.",
        "eng": "She finished ___ her homework.",
        "ans": "doing",
        "opts": [
          "to do",
          "do",
          "done",
          "doing"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q5",
        "kor": "도와주어서 고마워.",
        "eng": "Thank you for ___ me.",
        "ans": "helping",
        "opts": [
          "helped",
          "to help",
          "helping",
          "help"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q6",
        "kor": "창문 여는 것을 꺼리시나요?",
        "eng": "Do you mind ___ the window?",
        "ans": "opening",
        "opts": [
          "opened",
          "opening",
          "open",
          "to open"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q7",
        "kor": "그는 담배 피우는 것을 포기했다.",
        "eng": "He gave up ___.",
        "ans": "smoking",
        "opts": [
          "smoking",
          "smoke",
          "to smoke",
          "smoked"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q8",
        "kor": "외식하는 것 어때?",
        "eng": "How about ___ out?",
        "ans": "eating",
        "opts": [
          "eat",
          "to eat",
          "ate",
          "eating"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q9",
        "kor": "실수를 하는 것은 정상이다.",
        "eng": "___ mistakes is normal.",
        "ans": "Making",
        "opts": [
          "Makes",
          "To making",
          "Making",
          "Make"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q10",
        "kor": "나는 너를 보기를 고대한다.",
        "eng": "I look forward to ___ you.",
        "ans": "seeing",
        "opts": [
          "seen",
          "seeing",
          "see",
          "saw"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q1",
        "kor": "나는 지금 책을 읽고 있다.",
        "eng": "I ___ a book now.",
        "ans": "am reading",
        "opts": [
          "am reading",
          "is reading",
          "are reading",
          "reading"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q2",
        "kor": "그녀는 노래를 부르고 있다.",
        "eng": "She ___ a song.",
        "ans": "is singing",
        "opts": [
          "am singing",
          "are singing",
          "singing",
          "is singing"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q3",
        "kor": "그들은 축구를 하고 있다.",
        "eng": "They ___ soccer.",
        "ans": "are playing",
        "opts": [
          "am playing",
          "playing",
          "are playing",
          "is playing"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q4",
        "kor": "아기가 자고 있다.",
        "eng": "The baby ___.",
        "ans": "is sleeping",
        "opts": [
          "sleeping",
          "is sleeping",
          "are sleeping",
          "sleeps"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q5",
        "kor": "우리는 점심을 먹고 있다.",
        "eng": "We ___ lunch.",
        "ans": "are eating",
        "opts": [
          "are eating",
          "is eating",
          "eating",
          "eat"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q6",
        "kor": "비가 오고 있다.",
        "eng": "It ___.",
        "ans": "is raining",
        "opts": [
          "are raining",
          "rains",
          "raining",
          "is raining"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q7",
        "kor": "너는 잘 하고 있어.",
        "eng": "You ___ well.",
        "ans": "are doing",
        "opts": [
          "is doing",
          "doing",
          "are doing",
          "am doing"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q8",
        "kor": "개가 짖고 있다.",
        "eng": "The dog ___.",
        "ans": "is barking",
        "opts": [
          "barking",
          "is barking",
          "am barking",
          "are barking"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q9",
        "kor": "그들은 뛰지 않고 있다.",
        "eng": "They ___.",
        "ans": "are not running",
        "opts": [
          "are not running",
          "is not running",
          "not running",
          "run not"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s0q10",
        "kor": "그는 TV를 보고 있다.",
        "eng": "He ___ TV.",
        "ans": "is watching",
        "opts": [
          "are watching",
          "watch",
          "watching",
          "is watching"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q1",
        "kor": "나는 수영하는 것을 즐긴다.",
        "eng": "I enjoy ___.",
        "ans": "swimming",
        "opts": [
          "to swimming",
          "swims",
          "swimming",
          "swim"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q2",
        "kor": "걷는 것은 건강에 좋다.",
        "eng": "___ is good.",
        "ans": "Walking",
        "opts": [
          "Walked",
          "Walking",
          "Walk",
          "Walks"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q3",
        "kor": "내 취미는 사진 찍기다.",
        "eng": "My hobby is ___ pictures.",
        "ans": "taking",
        "opts": [
          "taking",
          "take",
          "to taking",
          "takes"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q4",
        "kor": "그녀는 숙제하기를 끝냈다.",
        "eng": "She finished ___ her homework.",
        "ans": "doing",
        "opts": [
          "do",
          "to do",
          "done",
          "doing"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q5",
        "kor": "도와준 것 고마워.",
        "eng": "Thanks for ___ me.",
        "ans": "helping",
        "opts": [
          "helped",
          "to help",
          "helping",
          "help"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q6",
        "kor": "문 여는 것 괜찮니?",
        "eng": "Do you mind ___ the door?",
        "ans": "opening",
        "opts": [
          "opened",
          "opening",
          "open",
          "to open"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q7",
        "kor": "그는 담배 피우는 것을 포기했다.",
        "eng": "He gave up ___.",
        "ans": "smoking",
        "opts": [
          "smoking",
          "smoke",
          "to smoke",
          "smoked"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q8",
        "kor": "외식하는 게 어때?",
        "eng": "How about ___ out?",
        "ans": "eating",
        "opts": [
          "eat",
          "to eat",
          "ate",
          "eating"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q9",
        "kor": "그는 대답을 피했다.",
        "eng": "He avoided ___.",
        "ans": "answering",
        "opts": [
          "to answer",
          "answered",
          "answering",
          "answer"
        ]
      },
      {
        "id": "g1_l2_gerund_basic_s1q10",
        "kor": "책 읽기는 재밌다.",
        "eng": "___ books is fun.",
        "ans": "Reading",
        "opts": [
          "Reads",
          "Reading",
          "Read",
          "To reading"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q1",
        "kor": "Mia는 지금 식물에 물을 주고 있다.",
        "eng": "Mia ___ the plants now.",
        "ans": "is watering",
        "opts": [
          "is watering",
          "waters",
          "watered",
          "watering"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q2",
        "kor": "그들은 지금 커피를 마시고 있다.",
        "eng": "They ___ coffee right now.",
        "ans": "are drinking",
        "opts": [
          "drink",
          "drinks",
          "drinking",
          "are drinking"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q3",
        "kor": "Tom은 지금 숙제를 하고 있지 않다. 그는 게임을 하고 있다.",
        "eng": "Tom ___ his homework now. He is playing a game.",
        "ans": "is not doing",
        "opts": [
          "isn't done",
          "not is doing",
          "is not doing",
          "doesn't do"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q4",
        "kor": "우리는 지금 수영 강습에 가는 중이다.",
        "eng": "We ___ to our swimming lesson now.",
        "ans": "are going",
        "opts": [
          "is going",
          "are going",
          "go",
          "goes"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q5",
        "kor": "Jake는 지금 우체국으로 뛰어가고 있다.",
        "eng": "Jake ___ to the post office now.",
        "ans": "is running",
        "opts": [
          "is running",
          "runs",
          "run",
          "running"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q6",
        "kor": "333번 버스가 지금 오고 있다.",
        "eng": "The 333 bus ___ now.",
        "ans": "is coming",
        "opts": [
          "comes",
          "come",
          "coming",
          "is coming"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q7",
        "kor": "학생들은 지금 프랑스어를 배우고 있다.",
        "eng": "The students ___ French now.",
        "ans": "are learning",
        "opts": [
          "learns",
          "learning",
          "are learning",
          "learn"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q8",
        "kor": "그 남자는 지금 컴퓨터를 고치고 있다.",
        "eng": "The man ___ the computer now.",
        "ans": "is fixing",
        "opts": [
          "fixing",
          "is fixing",
          "fixes",
          "fix"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q9",
        "kor": "Sophie는 지금 거울을 보고 있다.",
        "eng": "Sophie ___ in the mirror now.",
        "ans": "is looking",
        "opts": [
          "is looking",
          "looks",
          "look",
          "looking"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s0q10",
        "kor": "우리 가족은 지금 새 식당에서 저녁을 먹고 있다.",
        "eng": "My family ___ dinner at a new restaurant now.",
        "ans": "is having",
        "opts": [
          "has",
          "have",
          "having",
          "is having"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q1",
        "kor": "나는 친구를 한 시간 동안 계속 기다렸다.",
        "eng": "I kept ___ for one hour for my friend.",
        "ans": "waiting",
        "opts": [
          "to wait",
          "waited",
          "waiting",
          "wait"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q2",
        "kor": "Jake는 스키 타기를 즐겨서 매년 겨울에 스키장에 간다.",
        "eng": "Jake enjoys ___, so he goes to a ski resort every winter.",
        "ans": "skiing",
        "opts": [
          "skied",
          "skiing",
          "ski",
          "to ski"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q3",
        "kor": "Sophie는 일찍 일어나는 것을 포기했다.",
        "eng": "Sophie gave up ___ up early.",
        "ans": "waking",
        "opts": [
          "waking",
          "wake",
          "woke",
          "to wake"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q4",
        "kor": "나는 보고서를 다 쓰고 잠자리에 들었다.",
        "eng": "I finished ___ a paper and went to sleep.",
        "ans": "writing",
        "opts": [
          "write",
          "wrote",
          "to write",
          "writing"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q5",
        "kor": "많은 인도 사람들은 돼지고기 먹는 것을 피한다.",
        "eng": "Many Indian people avoid ___ pork.",
        "ans": "eating",
        "opts": [
          "ate",
          "to eat",
          "eating",
          "eat"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q6",
        "kor": "Nora는 오디션을 위해 노래 부르는 것을 연습한다.",
        "eng": "Nora practices ___ for the audition.",
        "ans": "singing",
        "opts": [
          "to sing",
          "singing",
          "sing",
          "sings"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q7",
        "kor": "냉장고가 갑자기 작동을 멈췄다.",
        "eng": "The refrigerator suddenly stopped ___.",
        "ans": "working",
        "opts": [
          "working",
          "work",
          "worked",
          "to work"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q8",
        "kor": "Ella는 강아지와 산책하는 것을 즐긴다.",
        "eng": "Ella enjoys ___ a walk with her dog.",
        "ans": "taking",
        "opts": [
          "take",
          "took",
          "to take",
          "taking"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q9",
        "kor": "나는 언젠가 일본을 방문하고 싶다.",
        "eng": "I want ___ Japan someday.",
        "ans": "to visit",
        "opts": [
          "visited",
          "visit",
          "to visit",
          "visiting"
        ]
      },
      {
        "id": "g1_l2_gerund_hard_s1q10",
        "kor": "불 좀 꺼주실래요?",
        "eng": "Would you mind ___ off the light?",
        "ans": "turning",
        "opts": [
          "to turn",
          "turning",
          "turn",
          "turned"
        ]
      }
    ]
  },
  "g1-l3": {
    "label": "중1 L3 · be동사 과거형",
    "color": "#22c55e",
    "questions": [
      {
        "id": "g1_l3_past_be_a1",
        "kor": "나는 작년에 열 살이었다.",
        "eng": "I ___ ten years old last year.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "am",
          "is"
        ]
      },
      {
        "id": "g1_l3_past_be_a2",
        "kor": "그들은 어제 공원에 있었다.",
        "eng": "They ___ in the park yesterday.",
        "ans": "were",
        "opts": [
          "was",
          "are",
          "be",
          "were"
        ]
      },
      {
        "id": "g1_l3_past_be_a3",
        "kor": "그녀는 방과 후 피곤했다.",
        "eng": "She ___ tired after school.",
        "ans": "was",
        "opts": [
          "is",
          "be",
          "was",
          "were"
        ]
      },
      {
        "id": "g1_l3_past_be_a4",
        "kor": "우리는 파티에 늦었다.",
        "eng": "We ___ late for the party.",
        "ans": "were",
        "opts": [
          "am",
          "were",
          "was",
          "is"
        ]
      },
      {
        "id": "g1_l3_past_be_a5",
        "kor": "시험은 매우 어려웠다.",
        "eng": "The test ___ very hard.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "are",
          "be"
        ]
      },
      {
        "id": "g1_l3_past_be_a6",
        "kor": "Tom과 Jina는 작년에 같은 반이었다.",
        "eng": "Tom and Jina ___ in the same class last year.",
        "ans": "were",
        "opts": [
          "was",
          "is",
          "are",
          "were"
        ]
      },
      {
        "id": "g1_l3_past_be_a7",
        "kor": "너는 오늘 아침에 집에 있었다.",
        "eng": "You ___ at home this morning.",
        "ans": "were",
        "opts": [
          "am",
          "is",
          "were",
          "was"
        ]
      },
      {
        "id": "g1_l3_past_be_a8",
        "kor": "내 강아지는 어제 아팠다.",
        "eng": "My dog ___ sick yesterday.",
        "ans": "was",
        "opts": [
          "be",
          "was",
          "were",
          "are"
        ]
      },
      {
        "id": "g1_l3_past_be_a9",
        "kor": "그 책들은 책상 위에 있었다.",
        "eng": "The books ___ on the desk.",
        "ans": "were",
        "opts": [
          "were",
          "was",
          "is",
          "am"
        ]
      },
      {
        "id": "g1_l3_past_be_a10",
        "kor": "지난 겨울은 춥고 눈이 많이 왔다.",
        "eng": "It ___ cold and snowy last winter.",
        "ans": "was",
        "opts": [
          "were",
          "are",
          "be",
          "was"
        ]
      },
      {
        "id": "g1_l3_past_be_b1",
        "kor": "그는 어제 학교에 없었다. 그는 집에 있었다.",
        "eng": "He ___ at school yesterday. He was at home.",
        "ans": "was not",
        "opts": [
          "not was",
          "is not",
          "was not",
          "were not"
        ]
      },
      {
        "id": "g1_l3_past_be_b2",
        "kor": "아이들은 박물관에서 조용하지 않았다.",
        "eng": "The children ___ quiet in the museum.",
        "ans": "were not",
        "opts": [
          "are not",
          "were not",
          "was not",
          "not were"
        ]
      },
      {
        "id": "g1_l3_past_be_b3",
        "kor": "날씨가 좋지 않았다. 비가 오고 바람이 불었다.",
        "eng": "The weather ___ nice. It was rainy and windy.",
        "ans": "was not",
        "opts": [
          "was not",
          "were not",
          "is not",
          "are not"
        ]
      },
      {
        "id": "g1_l3_past_be_b4",
        "kor": "나는 시험 전에 긴장하지 않았다. 나는 신이 났다!",
        "eng": "I ___ nervous before the test. I was excited!",
        "ans": "was not",
        "opts": [
          "were not",
          "am not",
          "is not",
          "was not"
        ]
      },
      {
        "id": "g1_l3_past_be_b5",
        "kor": "너는 오늘 오후에 도서관에 있었니? 응, 있었어.",
        "eng": "___ you at the library this afternoon? Yes, I was.",
        "ans": "Were",
        "opts": [
          "Is",
          "Are",
          "Were",
          "Was"
        ]
      },
      {
        "id": "g1_l3_past_be_b6",
        "kor": "그녀는 결과에 만족했니? 아니, 만족하지 않았어.",
        "eng": "___ she happy with the result? No, she wasn't.",
        "ans": "Was",
        "opts": [
          "Are",
          "Was",
          "Were",
          "Is"
        ]
      },
      {
        "id": "g1_l3_past_be_b7",
        "kor": "시험이 어려웠니? 아니, 어렵지 않았어.",
        "eng": "___ the test difficult? No, it wasn't.",
        "ans": "Was",
        "opts": [
          "Was",
          "Were",
          "Is",
          "Are"
        ]
      },
      {
        "id": "g1_l3_past_be_b8",
        "kor": "그들은 작년에 너의 반 친구였니? 응, 맞아.",
        "eng": "___ they your classmates last year? Yes, they were.",
        "ans": "Were",
        "opts": [
          "Was",
          "Is",
          "Are",
          "Were"
        ]
      },
      {
        "id": "g1_l3_past_be_b9",
        "kor": "나의 할아버지는 농부가 아니었다. 그는 의사였다.",
        "eng": "My grandfather ___ a farmer. He was a doctor.",
        "ans": "was not",
        "opts": [
          "is not",
          "are not",
          "was not",
          "were not"
        ]
      },
      {
        "id": "g1_l3_past_be_b10",
        "kor": "그 사과들은 신선하지 않았다. 그것들은 매우 오래되었다.",
        "eng": "The apples ___ fresh. They were very old.",
        "ans": "were not",
        "opts": [
          "are not",
          "were not",
          "was not",
          "is not"
        ]
      },
      {
        "id": "g1_l3_past_be_hard_a1",
        "kor": "선반 위의 상자는 비어 있었다. 나는 쿠키를 찾을 수 없었다.",
        "eng": "The box on the shelf ___ empty. I couldn't find the cookies.",
        "ans": "was",
        "opts": [
          "was",
          "were",
          "wasn't",
          "weren't"
        ]
      },
      {
        "id": "g1_l3_past_be_hard_a2",
        "kor": "Mia와 언니는 어제 오후에 도서관에 있었다.",
        "eng": "Mia and her sister ___ at the library yesterday afternoon.",
        "ans": "were",
        "opts": [
          "was",
          "weren't",
          "wasn't",
          "were"
        ]
      },
      {
        "id": "g1_l3_past_be_hard_a3",
        "kor": "수프가 너무 짜서 나는 많이 먹지 못했다.",
        "eng": "The soup ___ too salty, so I couldn't eat much of it.",
        "ans": "was",
        "opts": [
          "were",
          "wasn't",
          "was",
          "weren't"
        ]
      },
      {
        "id": "g1_l3_past_be_hard_a4",
        "kor": "내 친구들은 어젯밤 집에 없었다. 그들은 콘서트에 갔다.",
        "eng": "My friends ___ not at home last night. They went to a concert.",
        "ans": "were",
        "opts": [
          "weren't",
          "were",
          "was",
          "wasn't"
        ]
      }
    ]
  },
  "g1-l4": {
    "label": "중1 L4 · to부정사 & will/should",
    "color": "#f59e0b",
    "questions": [
      {
        "id": "g1_l4_to_will_basic_a1",
        "kor": "Mia는 나와 함께 탁구를 치고 싶어 한다.",
        "eng": "Mia wants ___ table tennis with me.",
        "ans": "to play",
        "opts": [
          "to play",
          "plays",
          "playing",
          "play"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a2",
        "kor": "그들은 제주도로 여행 가기로 결정했다.",
        "eng": "They decided ___ to Jeju Island.",
        "ans": "to travel",
        "opts": [
          "traveling",
          "travels",
          "travel",
          "to travel"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a3",
        "kor": "Sam은 매일 아침 버스에서 음악 듣는 것을 즐긴다.",
        "eng": "Sam enjoys ___ music on the bus every morning.",
        "ans": "listening",
        "opts": [
          "listens",
          "listened",
          "listening",
          "to listen"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a4",
        "kor": "나는 오늘 밤에 내 프로젝트를 끝내야 한다.",
        "eng": "I need ___ my project tonight.",
        "ans": "to finish",
        "opts": [
          "finishes",
          "to finish",
          "finish",
          "finishing"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a5",
        "kor": "Jake는 점심 후 과학 보고서 작성을 다 마쳤다.",
        "eng": "Jake finished ___ his science report after lunch.",
        "ans": "doing",
        "opts": [
          "doing",
          "to do",
          "does",
          "done"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a6",
        "kor": "우리는 버스 정류장에서 만나기로 합의했다.",
        "eng": "We agreed ___ at the bus stop.",
        "ans": "to meet",
        "opts": [
          "meets",
          "meeting",
          "meet",
          "to meet"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a7",
        "kor": "Tom은 그의 방을 깨끗하게 유지하기로 약속했다.",
        "eng": "Tom promised ___ his room clean.",
        "ans": "to keep",
        "opts": [
          "keeps",
          "kept",
          "to keep",
          "keeping"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a8",
        "kor": "그녀는 모든 시험에서 계속 같은 실수를 했다.",
        "eng": "She kept ___ the same mistake on every test.",
        "ans": "making",
        "opts": [
          "makes",
          "making",
          "to make",
          "made"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a9",
        "kor": "내 여동생은 지난 여름에 자전거 타는 법을 배웠다.",
        "eng": "My sister learned ___ a bike last summer.",
        "ans": "to ride",
        "opts": [
          "to ride",
          "riding",
          "rides",
          "rode"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_a10",
        "kor": "너는 금요일까지 양식을 제출해야 한다.",
        "eng": "You need ___ the form by Friday.",
        "ans": "to submit",
        "opts": [
          "submit",
          "submits",
          "submitting",
          "to submit"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b1",
        "kor": "너는 매일 에너지를 절약해야 한다.",
        "eng": "You ___ energy every day.",
        "ans": "should save",
        "opts": [
          "should saves",
          "should to save",
          "should save",
          "will save"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b2",
        "kor": "그녀는 내일 반 앞에서 발표를 할 것이다.",
        "eng": "She ___ a presentation in front of the class tomorrow.",
        "ans": "will do",
        "opts": [
          "will to do",
          "will do",
          "will does",
          "should do"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b3",
        "kor": "제가 오후 3시까지 거기에 도착해야 하나요?",
        "eng": "___ arrive there by 3 p.m.?",
        "ans": "Should I",
        "opts": [
          "Should I",
          "I should",
          "Do I should",
          "Am I should"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b4",
        "kor": "너는 지금 당장 책상을 정리할래?",
        "eng": "___ clean up your desk right now?",
        "ans": "Will you",
        "opts": [
          "Should you",
          "You will",
          "Will you to",
          "Will you"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b5",
        "kor": "우리는 오늘 오후에 공원에 가지 않을 것이다.",
        "eng": "We ___ go to the park this afternoon.",
        "ans": "will not",
        "opts": [
          "don't will",
          "won't not",
          "will not",
          "should not"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b6",
        "kor": "이번 주말은 따뜻하고 화창할 것이다.",
        "eng": "It ___ warm and sunny this weekend.",
        "ans": "will be",
        "opts": [
          "is will",
          "will be",
          "wills be",
          "will is"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b7",
        "kor": "너는 자전거를 탈 때 헬멧을 써야 한다.",
        "eng": "You ___ wear a helmet when you ride a bike.",
        "ans": "should",
        "opts": [
          "should",
          "shoulds",
          "should to",
          "are should"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b8",
        "kor": "Ben은 저녁 식사 전에 사탕을 먹으면 안 된다.",
        "eng": "Ben ___ eat candy before dinner.",
        "ans": "should not",
        "opts": [
          "not should",
          "doesn't should",
          "should not to",
          "should not"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b9",
        "kor": "우리 지금 떠나야 하나요? 네, 그래야 해요.",
        "eng": "___ we leave now? Yes, we should.",
        "ans": "Should",
        "opts": [
          "Are",
          "Will",
          "Should",
          "Do"
        ]
      },
      {
        "id": "g1_l4_to_will_basic_b10",
        "kor": "내가 오늘 밤에 너에게 전화할게.",
        "eng": "I ___ call you later tonight.",
        "ans": "will",
        "opts": [
          "do will",
          "will",
          "am will",
          "will to"
        ]
      },
      {
        "id": "g1_l4_to_will_hard_a1",
        "kor": "Sophie는 주말에 한국 드라마 보는 것을 즐긴다.",
        "eng": "Sophie enjoys ___ Korean dramas on weekends.",
        "ans": "watching",
        "opts": [
          "watching",
          "watch",
          "watches",
          "to watch"
        ]
      },
      {
        "id": "g1_l4_to_will_hard_a2",
        "kor": "너 정말 피곤해 보인다. 오늘 밤 일찍 자는 게 좋겠다.",
        "eng": "You look really tired. You ___ go to bed early tonight.",
        "ans": "should",
        "opts": [
          "will",
          "are",
          "do",
          "should"
        ]
      },
      {
        "id": "g1_l4_to_will_hard_a3",
        "kor": "서둘러! 버스가 5분 후에 도착할 거야.",
        "eng": "Hurry up! The bus will ___ in five minutes.",
        "ans": "arrive",
        "opts": [
          "to arrive",
          "arriving",
          "arrive",
          "arrives"
        ]
      },
      {
        "id": "g1_l4_to_will_hard_a4",
        "kor": "Max는 에세이에서 계속 같은 실수를 했다.",
        "eng": "Max kept ___ the same mistake in his essay.",
        "ans": "making",
        "opts": [
          "made",
          "making",
          "make",
          "to make"
        ]
      }
    ]
  },
  "g1-l5": {
    "label": "중1 L5 · 재귀대명사 & to부정사",
    "color": "#8b5cf6",
    "questions": [
      {
        "id": "g1_l5_reflexive_to_basic_a1",
        "kor": "Sarah는 자기 자신을 위해 새 가방을 샀다.",
        "eng": "Sarah bought a new bag for ___.",
        "ans": "herself",
        "opts": [
          "herself",
          "her",
          "hers",
          "she"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a2",
        "kor": "나는 지난 주말 하이킹 중에 다쳤다.",
        "eng": "I hurt ___ while hiking last weekend.",
        "ans": "myself",
        "opts": [
          "me",
          "my",
          "mine",
          "myself"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a3",
        "kor": "우리는 매일 우리 자신을 믿는다.",
        "eng": "We believe in ___ every day.",
        "ans": "ourselves",
        "opts": [
          "our",
          "ourself",
          "ourselves",
          "us"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a4",
        "kor": "남학생들, 반 친구들에게 자기소개를 해 주세요.",
        "eng": "Boys, please introduce ___ to the class.",
        "ans": "yourselves",
        "opts": [
          "yourselve",
          "yourselves",
          "yourself",
          "yours"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a5",
        "kor": "고양이가 거울에서 자기 자신을 본다.",
        "eng": "The cat sees ___ in the mirror.",
        "ans": "itself",
        "opts": [
          "itself",
          "it",
          "its",
          "itselves"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a6",
        "kor": "학생들이 직접 부서진 의자를 고쳤다.",
        "eng": "The students fixed the broken chairs by ___.",
        "ans": "themselves",
        "opts": [
          "themself",
          "they",
          "theirs",
          "themselves"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a7",
        "kor": "내 남동생은 어제 뉴스에서 자신을 보았다.",
        "eng": "My brother saw ___ on the news yesterday.",
        "ans": "himself",
        "opts": [
          "his",
          "he",
          "himself",
          "him"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a8",
        "kor": "나에게 네 자신에 대해 말해 줘, Mia.",
        "eng": "Tell me about ___, Mia.",
        "ans": "yourself",
        "opts": [
          "yourselves",
          "yourself",
          "you",
          "your"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a9",
        "kor": "로봇이 스스로 전원을 껐다.",
        "eng": "The robot turned ___ off.",
        "ans": "itself",
        "opts": [
          "itself",
          "it",
          "its",
          "themself"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_a10",
        "kor": "아이들은 놀고 나서 스스로 몸을 씻었다.",
        "eng": "The children washed ___ after playing.",
        "ans": "themselves",
        "opts": [
          "them",
          "themself",
          "their",
          "themselves"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b1",
        "kor": "유나는 책을 읽으러 도서관에 갔다.",
        "eng": "Yuna went to the library ___ a book.",
        "ans": "to read",
        "opts": [
          "reading",
          "reads",
          "to read",
          "read"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b2",
        "kor": "에밀리는 그림용 태블릿을 사기 위해 아르바이트를 했다.",
        "eng": "Emily worked part-time ___ a tablet for drawing.",
        "ans": "to buy",
        "opts": [
          "buys",
          "to buy",
          "buy",
          "bought"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b3",
        "kor": "그는 시험에 합격하기 위해 열심히 공부했다.👉 want/plan/decide + to부정사 → 동사의 목적어, 동사 뒤 to부정사 → 목적(~하기 위해)",
        "eng": "목적('~하기 위해')의 to부정사가 쓰인 문장을 고르시오.",
        "ans": "He studied hard to pass the exam.",
        "opts": [
          "He studied hard to pass the exam.",
          "I want to visit Paris.",
          "She plans to become a nurse.",
          "We decided to move to Busan."
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b4",
        "kor": "Noah는 결석을 설명하기 위해 선생님께 문자를 보냈다.",
        "eng": "Noah texted his teacher ___ his absence.",
        "ans": "to explain",
        "opts": [
          "explain",
          "explained",
          "explaining",
          "to explain"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b5",
        "kor": "그녀는 대회에서 이기기 위해 매일 연습했다.",
        "eng": "She practiced every day ___ the contest.",
        "ans": "to win",
        "opts": [
          "winning",
          "wins",
          "to win",
          "win"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b6",
        "kor": "그녀는 채소를 사기 위해 시장에 갔다.👉 went(동작)의 목적을 설명하는 to부정사: ~하기 위해",
        "eng": "다음 문장의 올바른 해석을 고르시오.She went to the market to buy vegetables.",
        "ans": "그녀는 채소를 사기 위해 시장에 갔다.",
        "opts": [
          "그녀는 채소를 팔기 위해 시장에 갔다.",
          "그녀는 채소를 사기 위해 시장에 갔다.",
          "그녀는 채소를 사는 것을 좋아해서 시장에 갔다.",
          "그녀는 시장에 가서 채소를 사기로 결정했다."
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b7",
        "kor": "그들은 교통체증을 피하기 위해 일찍 출발했다.",
        "eng": "They left early ___ the traffic.",
        "ans": "to avoid",
        "opts": [
          "to avoid",
          "avoid",
          "avoiding",
          "avoids"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b8",
        "kor": "엄마는 우리 모두를 위해 저녁을 요리하셨다.",
        "eng": "Mom cooked dinner ___ us all.",
        "ans": "to feed",
        "opts": [
          "feed",
          "feeding",
          "feeds",
          "to feed"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b9",
        "kor": "그들은 전기를 절약하기 위해 불을 껐다.👉 need/plan/promise + to부정사 → 동사의 목적어, 동작 뒤 to부정사 → 목적(~하기 위해)",
        "eng": "밑줄 친 to부정사가 '목적(~하기 위해)'으로 쓰인 것을 고르시오.",
        "ans": "They turned off the lights to save power.",
        "opts": [
          "She plans to travel to Japan.",
          "Tom promised to be on time.",
          "They turned off the lights to save power.",
          "I need to sleep more."
        ]
      },
      {
        "id": "g1_l5_reflexive_to_basic_b10",
        "kor": "나는 새로운 단어를 배우기 위해 이 앱을 사용한다.",
        "eng": "I use this app ___ new words.",
        "ans": "to learn",
        "opts": [
          "learning",
          "to learn",
          "learn",
          "learned"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_hard_a1",
        "kor": "Jaeho는 과학 과제를 위한 책을 빌리러 도서관에 갔다.",
        "eng": "Jaeho went to the library ___ a book for his science project.",
        "ans": "to borrow",
        "opts": [
          "to borrow",
          "borrows",
          "borrowing",
          "borrowed"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_hard_a2",
        "kor": "아이들은 나무 위 오두막을 스스로 지었다.",
        "eng": "The kids built the treehouse by ___.",
        "ans": "themselves",
        "opts": [
          "them",
          "themself",
          "theirs",
          "themselves"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_hard_a3",
        "kor": "나는 생일에 나 자신에게 작은 선물을 샀다.",
        "eng": "I bought ___ a small gift on my birthday.",
        "ans": "myself",
        "opts": [
          "my",
          "I",
          "myself",
          "me"
        ]
      },
      {
        "id": "g1_l5_reflexive_to_hard_a4",
        "kor": "그들은 자선 단체를 위해 돈을 모으기 위해 베이크 세일을 열었다.",
        "eng": "목적('~하기 위해')의 to부정사가 쓰인 문장을 고르시오.",
        "ans": "They held a bake sale to raise money for charity.",
        "opts": [
          "We plan to visit the science museum.",
          "They held a bake sale to raise money for charity.",
          "She wants to become a nurse.",
          "He decided to stay home all day."
        ]
      },
      {
        "id": "g1_l5_reflexive_to_hard_a9",
        "kor": "그녀는 숲에서 나가는 길을 찾기 위해 지도를 읽었다.",
        "eng": "다음 문장의 올바른 해석을 고르시오.She read the map to find the way out of the forest.",
        "ans": "그녀는 숲에서 나가는 길을 찾기 위해 지도를 읽었다.",
        "opts": [
          "그녀는 숲에서 나가는 길을 찾기 위해 지도를 읽었다.",
          "그녀는 지도 읽기를 원해서 숲 밖으로 나갔다.",
          "그녀는 지도를 읽으면서 숲속에서 길을 잃었다.",
          "그녀는 숲 지도를 읽어서 길을 결정했다."
        ]
      }
    ]
  },
  "g1-l6": {
    "label": "중1 L6 · 감각동사 & because",
    "color": "#ef4444",
    "questions": [
      {
        "id": "g1_l6_look_because_basic_a1",
        "kor": "새 놀이터는 매우 안전해 보인다.",
        "eng": "The new playground looks very ___.",
        "ans": "safe",
        "opts": [
          "safe",
          "safely",
          "safety",
          "safeness"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a2",
        "kor": "Jake의 그림은 창의적으로 보인다.",
        "eng": "Jake's drawing looks ___.",
        "ans": "creative",
        "opts": [
          "creatively",
          "creation",
          "creating",
          "creative"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a3",
        "kor": "학교 뒤편의 작은 정원은 사랑스러워 보인다.",
        "eng": "The small garden behind the school looks ___.",
        "ans": "lovely",
        "opts": [
          "lovingly",
          "loveliness",
          "lovely",
          "love"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a4",
        "kor": "내 남동생은 경기 전에 매우 긴장해 보인다.",
        "eng": "My brother looks very ___ before the game.",
        "ans": "nervous",
        "opts": [
          "nerve",
          "nervous",
          "nervously",
          "nervousness"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a5",
        "kor": "거리 시장은 주말에 매우 활기차 보인다.",
        "eng": "The street market looks very ___ on weekends.",
        "ans": "lively",
        "opts": [
          "lively",
          "livelily",
          "live",
          "livelihood"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a6",
        "kor": "축제의 라이브 음악은 정말 멋지게 들린다.",
        "eng": "The live music at the festival sounds ___.",
        "ans": "amazing",
        "opts": [
          "amazingly",
          "amaze",
          "amazed",
          "amazing"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a7",
        "kor": "바구니 안의 아기 고양이들은 사랑스러워 보인다.",
        "eng": "The kittens in the basket look ___.",
        "ans": "adorable",
        "opts": [
          "adore",
          "adoration",
          "adorable",
          "adorably"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a8",
        "kor": "새 코치는 모두에게 매우 친절해 보인다.",
        "eng": "The new coach looks very ___ to everyone.",
        "ans": "friendly",
        "opts": [
          "friend",
          "friendly",
          "friendliness",
          "friendship"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a9",
        "kor": "마당의 장미는 훌륭한 향기가 난다.",
        "eng": "The roses in the yard smell ___.",
        "ans": "wonderful",
        "opts": [
          "wonderful",
          "wonderfully",
          "wonder",
          "wondering"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_a10",
        "kor": "이 레몬 사탕은 매우 새콤한 맛이 난다.",
        "eng": "This lemon candy tastes very ___.",
        "ans": "sour",
        "opts": [
          "sourly",
          "sourness",
          "souring",
          "sour"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b1",
        "kor": "우리는 집 안에 머물렀다.",
        "eng": "We stayed inside ___.",
        "ans": "because it was raining heavily",
        "opts": [
          "because we wanted to go out",
          "because the sun was bright",
          "because it was raining heavily",
          "because the weather was nice"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b2",
        "kor": "Jaden은 조금만 먹었다.",
        "eng": "Jaden ate only a little ___.",
        "ans": "because he wasn't feeling well",
        "opts": [
          "because the meal looked delicious",
          "because he wasn't feeling well",
          "because he was very hungry",
          "because he loved the food"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b3",
        "kor": "그녀는 스쿨버스를 놓쳤다.",
        "eng": "___, she missed the school bus.",
        "ans": "Because she got up late",
        "opts": [
          "Because she got up late",
          "Because she left home early",
          "Because she was on time",
          "When she ran fast"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b4",
        "kor": "Tom은 TV를 껐다.",
        "eng": "Tom turned off the TV ___.",
        "ans": "because he needed to study",
        "opts": [
          "because he wanted to watch more",
          "because it was his favorite show",
          "because the show was interesting",
          "because he needed to study"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b5",
        "kor": "우리는 소풍을 갈 수 없었다.",
        "eng": "___, we couldn't go on the picnic.",
        "ans": "Because there was a big storm",
        "opts": [
          "Because everyone wanted to go",
          "When we had enough food",
          "Because there was a big storm",
          "Because the weather was sunny"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b6",
        "kor": "Leo는 내 우산을 빌렸다.",
        "eng": "Leo borrowed my umbrella ___.",
        "ans": "because he forgot his own",
        "opts": [
          "because it wasn't raining",
          "because he forgot his own",
          "because it was a hot day",
          "because he had one already"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b7",
        "kor": "Amy는 시험에서 만점을 받았다.",
        "eng": "Amy got a perfect score on the test ___.",
        "ans": "because she reviewed her notes every day",
        "opts": [
          "because she reviewed her notes every day",
          "because she didn't study at all",
          "because she played all day",
          "because she forgot the material"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b8",
        "kor": "우리는 의자를 추가로 주문했다.",
        "eng": "___, we ordered extra chairs.",
        "ans": "Because we were expecting many visitors",
        "opts": [
          "Because there were enough seats",
          "Because only a few guests came",
          "Because the room was empty",
          "Because we were expecting many visitors"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b9",
        "kor": "Sam은 선크림을 발랐다.",
        "eng": "Sam put on sunscreen ___.",
        "ans": "because the sun was very strong",
        "opts": [
          "because he didn't like the beach",
          "because he wanted to stay inside",
          "because the sun was very strong",
          "because it was a cloudy day"
        ]
      },
      {
        "id": "g1_l6_look_because_basic_b10",
        "kor": "Nora는 일찍 잠자리에 들었다.",
        "eng": "Nora went to bed early ___.",
        "ans": "because she had an early practice the next day",
        "opts": [
          "because she finished homework late",
          "because she had an early practice the next day",
          "because she wasn't tired",
          "because she wanted to stay up late"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_a3",
        "kor": "그 축제는 훌륭해 보인다.",
        "eng": "The festival looks ___. 빈칸에 들어갈 알맞은 말을 고르세요. festival 축제",
        "ans": "wonderful",
        "opts": [
          "wonderful",
          "wonderfully",
          "wonder",
          "wondering"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_a4",
        "kor": "우리는 날씨가 위험해 보였기 때문에 등산을 취소했다.",
        "eng": "We canceled the hike ___ the weather looked dangerous. cancel 취소하다hike 등산, 하이킹dangerous 위험한",
        "ans": "because",
        "opts": [
          "so",
          "when",
          "but",
          "because"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b1",
        "kor": "그 프로젝트들은 놀라워 보였다.",
        "eng": "The projects looked ___.",
        "ans": "amazing",
        "opts": [
          "amazement",
          "amaze",
          "amazing",
          "amazingly"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b2",
        "kor": "Maya의 모형은 모든 사람에게 특히 인상적으로 보였다.",
        "eng": "Maya's model looked especially ___ to everyone.",
        "ans": "impressive",
        "opts": [
          "impress",
          "impressive",
          "impressively",
          "impression"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b3",
        "kor": "화려한 전시물들은 활기차고 생동감 넘쳐 보였다.",
        "eng": "The colorful displays looked ___ and full of energy.",
        "ans": "lively",
        "opts": [
          "lively",
          "brightly",
          "live",
          "liveliness"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b4",
        "kor": "Jake의 로봇은 사실적이고 매우 현대적으로 보였다.",
        "eng": "Jake's robot looked ___ and very modern.",
        "ans": "realistic",
        "opts": [
          "realistically",
          "realism",
          "realize",
          "realistic"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b5",
        "kor": "우리 모두 그 행사가 결국 훌륭해 보였다는 데 동의했다.",
        "eng": "We all agreed the fair looked ___ in the end.",
        "ans": "great",
        "opts": [
          "greatness",
          "greatly good",
          "great",
          "greatly"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b6",
        "kor": "날씨가 끔찍했기 때문에 우리 학교 여행이 취소되었다.",
        "eng": "Our school trip was canceled ___ the weather was terrible.",
        "ans": "because",
        "opts": [
          "when",
          "because",
          "so",
          "but"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b7",
        "kor": "많은 학생들이 실망했기 때문에 선생님들은 대신 실내 활동을 계획했다.",
        "eng": "___ many students felt disappointed, the teachers planned an indoor activity instead.",
        "ans": "Because",
        "opts": [
          "Because",
          "So",
          "But",
          "When"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b8",
        "kor": "버스를 이용할 수 없었기 때문에 우리는 박물관을 방문할 수 없었다.",
        "eng": "We couldn't visit the museum ___ the buses weren't available.",
        "ans": "because",
        "opts": [
          "so",
          "but",
          "and",
          "because"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b9",
        "kor": "실내 활동이 재미있었기 때문에 모든 사람이 즐거운 시간을 보냈다.",
        "eng": "___ the indoor activity turned out to be fun, everyone had a great time.",
        "ans": "Because",
        "opts": [
          "Although",
          "So",
          "Because",
          "Since"
        ]
      },
      {
        "id": "g1_l6_look_because_hard_b10",
        "kor": "Jake는 새 보드게임을 해볼 수 있었기 때문에 특히 행복했다.",
        "eng": "Jake was especially happy ___ he got to try the new board game.",
        "ans": "because",
        "opts": [
          "although",
          "because",
          "so",
          "when"
        ]
      }
    ]
  },
  "g2-l1": {
    "label": "중2 L1 · 수여동사 & 관계대명사",
    "color": "#0d9488",
    "questions": [
      {
        "id": "g2_l1_g2_give_relclause_basic_a1",
        "kor": "그녀는 경기 후 나에게 따뜻한 포옹을 해 주었다.",
        "eng": "She gave ___ a warm hug after the game.",
        "ans": "me",
        "opts": [
          "me",
          "I",
          "my",
          "mine"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a2",
        "kor": "아빠는 자기 전에 우리에게 재미있는 이야기를 해 주셨다.",
        "eng": "My dad told ___ a funny story before bed.",
        "ans": "us",
        "opts": [
          "we",
          "our",
          "ours",
          "us"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a3",
        "kor": "Jake는 그들에게 자신의 새 로봇 모델을 보여주었다.",
        "eng": "Jake showed ___ his new robot model.",
        "ans": "them",
        "opts": [
          "their",
          "theirs",
          "them",
          "they"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a4",
        "kor": "할머니가 그에게 새 겨울 코트를 사 주셨다.",
        "eng": "Grandma bought ___ a new winter coat.",
        "ans": "him",
        "opts": [
          "himself",
          "him",
          "he",
          "his"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a5",
        "kor": "사서가 그녀에게 천문학 책 세 권을 빌려주었다.",
        "eng": "The librarian lent ___ three books on astronomy.",
        "ans": "her",
        "opts": [
          "her",
          "she",
          "hers",
          "herself"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a6",
        "kor": "그녀는 방과 후 그에게 새 노트를 주었다.",
        "eng": "She gave a new notebook ___ him after school.",
        "ans": "to",
        "opts": [
          "for",
          "of",
          "by",
          "to"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a7",
        "kor": "할아버지가 우리에게 나무 새집을 만들어 주셨다.",
        "eng": "Grandpa made a wooden birdhouse ___ us.",
        "ans": "for",
        "opts": [
          "of",
          "at",
          "for",
          "to"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_a8",
        "kor": "언니가 나에게 귀여운 스카프를 사 주었다.",
        "eng": "My sister bought a cute scarf ___ me.",
        "ans": "for",
        "opts": [
          "with",
          "for",
          "to",
          "of"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b1",
        "kor": "나는 바이올린을 정말 잘 연주하는 사촌이 있다.",
        "eng": "I have a cousin ___ plays the violin really well.",
        "ans": "who",
        "opts": [
          "who",
          "which",
          "what",
          "whom"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b2",
        "kor": "우리는 혼자서 집을 청소할 수 있는 로봇을 가지고 있다.",
        "eng": "We have a robot ___ can clean the house by itself.",
        "ans": "that",
        "opts": [
          "who",
          "whom",
          "what",
          "that"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b3",
        "kor": "그녀는 어린이 병원에서 일하는 간호사이다.",
        "eng": "She is a nurse ___ works at the children's hospital.",
        "ans": "who",
        "opts": [
          "what",
          "whom",
          "who",
          "which"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b4",
        "kor": "그는 차 밑에 숨어 있던 길고양이를 발견했다.",
        "eng": "He found a stray cat ___ was hiding under the car.",
        "ans": "which",
        "opts": [
          "what",
          "which",
          "who",
          "whom"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b5",
        "kor": "Leo는 항상 수업에 일찍 오는 학생이다.",
        "eng": "Leo is a student ___ always arrives early to class.",
        "ans": "who",
        "opts": [
          "who",
          "which",
          "what",
          "whom"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b6",
        "kor": "그녀는 먼 행성을 배경으로 한 책을 읽었다.",
        "eng": "She read a book ___ was set on a distant planet.",
        "ans": "that",
        "opts": [
          "who",
          "whom",
          "what",
          "that"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b7",
        "kor": "우리 학교에는 허브와 채소를 기르는 정원이 있다.",
        "eng": "My school has a garden ___ grows herbs and vegetables.",
        "ans": "that",
        "opts": [
          "whom",
          "what",
          "that",
          "who"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_basic_b8",
        "kor": "Nora는 50개 이상의 단어를 말할 수 있는 앵무새를 키우고 있다.",
        "eng": "Nora has a parrot ___ can say over fifty words.",
        "ans": "that",
        "opts": [
          "whose",
          "that",
          "who",
          "whom"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_hard_a1",
        "kor": "우리 삼촌이 어젯밤 우리에게 흥미로운 이야기를 해 주셨다.",
        "eng": "My uncle told ___ an interesting story last night.",
        "ans": "us",
        "opts": [
          "us",
          "for us",
          "to us",
          "ours"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_hard_a2",
        "kor": "아빠는 일요일에 온 가족을 위해 푸짐한 식사를 만들어 주셨다.",
        "eng": "Dad cooked a big meal ___ the whole family on Sunday.",
        "ans": "for",
        "opts": [
          "to",
          "with",
          "of",
          "for"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_hard_a3",
        "kor": "나는 정원에서 아름다운 장미를 키우는 이웃이 있다.",
        "eng": "I have a neighbor ___ grows beautiful roses in her garden.",
        "ans": "who",
        "opts": [
          "what",
          "where",
          "who",
          "which"
        ]
      },
      {
        "id": "g2_l1_g2_give_relclause_hard_a4",
        "kor": "그녀는 벤치에 놓여 있던 지갑을 발견했다.",
        "eng": "She found a wallet ___ was left on the bench.",
        "ans": "which",
        "opts": [
          "where",
          "which",
          "who",
          "what"
        ]
      }
    ]
  },
  "g2-l2": {
    "label": "중2 L2 · 현재완료 & 비교급",
    "color": "#f97316",
    "questions": [
      {
        "id": "g2_l2_g2_perfect_compare_basic_a1",
        "kor": "나는 이 영화를 전에 본 적이 있다.",
        "eng": "I ___ seen this film before.",
        "ans": "have",
        "opts": [
          "have",
          "has",
          "had",
          "do"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a2",
        "kor": "그녀는 방금 숙제를 끝냈다.",
        "eng": "She ___ just finished her homework.",
        "ans": "has",
        "opts": [
          "have",
          "had",
          "does",
          "has"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a3",
        "kor": "그들은 10년 동안 여기서 살아 왔다.",
        "eng": "They ___ lived here for ten years.",
        "ans": "have",
        "opts": [
          "had",
          "having",
          "have",
          "has"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a4",
        "kor": "우리 아빠는 이미 저녁을 드셨다.",
        "eng": "My dad ___ already eaten dinner.",
        "ans": "has",
        "opts": [
          "was",
          "has",
          "have",
          "had"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a5",
        "kor": "Jake와 나는 한 번도 초밥을 먹어본 적이 없다.",
        "eng": "Jake and I ___ never tried sushi.",
        "ans": "have",
        "opts": [
          "have",
          "has",
          "had",
          "were"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a6",
        "kor": "Mia는 올해 소설 세 편을 썼다.",
        "eng": "Mia ___ three novels this year.",
        "ans": "has written",
        "opts": [
          "has wrote",
          "have written",
          "is writing",
          "has written"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a7",
        "kor": "우리는 이 노래를 전에 들어본 적이 있다.",
        "eng": "We ___ this song before.",
        "ans": "have heard",
        "opts": [
          "has heard",
          "are heard",
          "have heard",
          "have hear"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a8",
        "kor": "그는 또 휴대폰을 망가뜨렸다.",
        "eng": "He ___ his phone again.",
        "ans": "has broken",
        "opts": [
          "was broken",
          "has broken",
          "has broke",
          "have broken"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a9",
        "kor": "그녀는 어렸을 때부터 기타를 연주해 왔다.",
        "eng": "She ___ the guitar since she was little.",
        "ans": "has played",
        "opts": [
          "has played",
          "has playing",
          "is played",
          "have played"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a17",
        "kor": "Jake는 세 달 동안 한국어를 공부해 왔다.",
        "eng": "Jake has studied Korean ___ three months.",
        "ans": "for",
        "opts": [
          "since",
          "in",
          "at",
          "for"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a18",
        "kor": "그녀는 2021년부터 서울에 살아 왔다.",
        "eng": "She has lived in Seoul ___ 2021.",
        "ans": "since",
        "opts": [
          "during",
          "from",
          "since",
          "for"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a19",
        "kor": "나는 오늘 아침부터 아무것도 먹지 않았다.",
        "eng": "I have not eaten anything ___ this morning.",
        "ans": "since",
        "opts": [
          "in",
          "since",
          "for",
          "at"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_a20",
        "kor": "우리는 오랜 세월 동안 절친한 친구로 지내 왔다.",
        "eng": "We have been best friends ___ many years.",
        "ans": "for",
        "opts": [
          "for",
          "since",
          "during",
          "from"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b1",
        "kor": "이 가방이 내 것보다 더 가볍다.",
        "eng": "This bag is ___ (light) than mine.",
        "ans": "lighter",
        "opts": [
          "more light",
          "lightest",
          "most light",
          "lighter"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b2",
        "kor": "나에게는 수학이 영어보다 더 어렵다.",
        "eng": "Math is ___ (difficult) than English for me.",
        "ans": "more difficult",
        "opts": [
          "most difficult",
          "difficultly",
          "more difficult",
          "difficulter"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b3",
        "kor": "그녀는 오빠보다 더 빨리 달린다.",
        "eng": "She runs ___ (fast) than her brother.",
        "ans": "faster",
        "opts": [
          "most fast",
          "faster",
          "more fast",
          "fastest"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b4",
        "kor": "이 소파가 저 의자보다 더 편안하다.",
        "eng": "This sofa is ___ (comfortable) than that chair.",
        "ans": "more comfortable",
        "opts": [
          "more comfortable",
          "comfortabler",
          "most comfortable",
          "comfortablest"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b5",
        "kor": "오늘은 어제보다 더 덥다.",
        "eng": "Today is ___ (hot) than yesterday.",
        "ans": "hotter",
        "opts": [
          "more hot",
          "hottest",
          "hoter",
          "hotter"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b6",
        "kor": "그는 팀에서 가장 키가 큰 선수다.",
        "eng": "He is ___ (tall) player on the team.",
        "ans": "the tallest",
        "opts": [
          "tallest",
          "most tallest",
          "the tallest",
          "taller"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b7",
        "kor": "이것은 가게에서 가장 비싼 시계다.",
        "eng": "This is ___ (expensive) watch in the shop.",
        "ans": "the most expensive",
        "opts": [
          "expensivest",
          "the most expensive",
          "more expensive",
          "most expensive"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_basic_b8",
        "kor": "그녀는 우리 반에서 가장 우수한 학생이다.",
        "eng": "She is ___ (good) student in our class.",
        "ans": "the best",
        "opts": [
          "the best",
          "the better",
          "the most good",
          "gooder"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_hard_a1",
        "kor": "그녀는 10년 동안 서울에 살고 있다.",
        "eng": "She ___ lived in Seoul for ten years.",
        "ans": "has",
        "opts": [
          "have",
          "had",
          "is",
          "has"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_hard_a2",
        "kor": "Tom은 일곱 살 때부터 피아노를 공부해 왔다.",
        "eng": "Tom has studied piano ___ he was seven years old.",
        "ans": "since",
        "opts": [
          "at",
          "from",
          "since",
          "for"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_hard_a3",
        "kor": "이 책은 내가 지난주에 읽은 것보다 더 흥미롭다.",
        "eng": "This book is ___ than the one I read last week.",
        "ans": "more interesting",
        "opts": [
          "the most interesting",
          "more interesting",
          "most interesting",
          "more interestingly"
        ]
      },
      {
        "id": "g2_l2_g2_perfect_compare_hard_a4",
        "kor": "Jake는 전교에서 키가 가장 큰 학생이다.",
        "eng": "Jake is ___ student in the whole school.",
        "ans": "the tallest",
        "opts": [
          "the tallest",
          "tallest",
          "the taller",
          "most tall"
        ]
      }
    ]
  },
  "g2-l3": {
    "label": "중2 L3 · 형용사 to부정사 & if",
    "color": "#ec4899",
    "questions": [
      {
        "id": "g2_l3_g2_to_if_basic_a1",
        "kor": "소풍에 먹을 것이 필요하다.",
        "eng": "I need something ___ for the picnic.",
        "ans": "to eat",
        "opts": [
          "to eat",
          "eating",
          "eat",
          "eaten"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a2",
        "kor": "그녀는 월요일까지 제출해야 할 보고서가 많다.",
        "eng": "She has a lot of reports ___ by Monday.",
        "ans": "to submit",
        "opts": [
          "submitting",
          "submitted",
          "submit",
          "to submit"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a3",
        "kor": "그는 방과 후 공부할 조용한 구석을 찾았다.",
        "eng": "He found a quiet corner ___ after school.",
        "ans": "to study",
        "opts": [
          "studied",
          "studying",
          "to study",
          "study"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a4",
        "kor": "떠나기 전에 발표할 것이 있나요?",
        "eng": "Do you have anything ___ before leaving?",
        "ans": "to announce",
        "opts": [
          "announce",
          "to announce",
          "announcing",
          "announced"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a5",
        "kor": "그들은 도시를 안내해 줄 가이드를 찾고 있다.",
        "eng": "They are looking for a guide ___ them around the city.",
        "ans": "to show",
        "opts": [
          "to show",
          "showing",
          "show",
          "shown"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a6",
        "kor": "이 공원에는 앉을 벤치가 없다.",
        "eng": "There is no bench ___ in this park.",
        "ans": "to sit on",
        "opts": [
          "to sit",
          "sit on",
          "sitting on",
          "to sit on"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a7",
        "kor": "그는 필기할 펜을 가져왔다.",
        "eng": "He brought a pen ___.",
        "ans": "to write with",
        "opts": [
          "write with",
          "writing with",
          "to write with",
          "to write"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a8",
        "kor": "그녀는 이야기할 주제를 찾고 있다.",
        "eng": "She is looking for a topic ___.",
        "ans": "to talk about",
        "opts": [
          "to talk",
          "to talk about",
          "talk about",
          "talking about"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_a9",
        "kor": "그는 하이킹 중 마실 물병을 가져왔다.",
        "eng": "He brought a bottle ___ on the hike.",
        "ans": "to drink from",
        "opts": [
          "to drink from",
          "to drink",
          "drink from",
          "drinking from"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_b1",
        "kor": "내일 비가 오면, 우리는 여행을 취소할 것이다.",
        "eng": "If it ___ tomorrow, we will cancel the trip.",
        "ans": "rains",
        "opts": [
          "will rain",
          "rained",
          "is raining",
          "rains"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_b2",
        "kor": "도움이 필요하면 그녀가 전화할 것이다.",
        "eng": "She will call you if she ___ any help.",
        "ans": "needs",
        "opts": [
          "needed",
          "is needing",
          "needs",
          "will need"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_b3",
        "kor": "그가 곧 도착하지 않으면 우리는 그 없이 시작할 것이다.",
        "eng": "We will start without him if he ___ soon.",
        "ans": "doesn't arrive",
        "opts": [
          "hasn't arrived",
          "doesn't arrive",
          "won't arrive",
          "didn't arrive"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_b4",
        "kor": "이번 주말 날씨가 좋으면, 캠핑 가자.",
        "eng": "If the weather ___ nice this weekend, let's go camping.",
        "ans": "is",
        "opts": [
          "is",
          "will be",
          "was",
          "being"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_basic_b5",
        "kor": "일찍 출발하지 않으면 기차를 놓칠 것이다.",
        "eng": "You'll miss the train if you ___ early.",
        "ans": "don't leave",
        "opts": [
          "won't leave",
          "didn't leave",
          "not leave",
          "don't leave"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_hard_a1",
        "kor": "Jake는 긴 버스 여행 중에 읽을 것이 필요하다.",
        "eng": "Jake needs something ___ on the long bus ride.",
        "ans": "to read",
        "opts": [
          "reading",
          "reads",
          "to read",
          "to reading"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_hard_a2",
        "kor": "우리는 햇볕 아래 앉을 벤치를 찾고 있다.",
        "eng": "We are looking for a bench ___ in the sun.",
        "ans": "to sit on",
        "opts": [
          "sits on",
          "to sit on",
          "sitting on",
          "to sitting on"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_hard_a3",
        "kor": "이번 토요일에 비가 오면 체육대회 일정이 변경될 것이다.",
        "eng": "If it ___ this Saturday, the sports day will be rescheduled.",
        "ans": "rains",
        "opts": [
          "rains",
          "will rain",
          "is raining",
          "rained"
        ]
      },
      {
        "id": "g2_l3_g2_to_if_hard_a4",
        "kor": "다음 주까지 반납하면 그 책을 가지고 있어도 된다.",
        "eng": "You can keep the book if you ___ it by next week.",
        "ans": "return",
        "opts": [
          "will return",
          "returned",
          "to return",
          "return"
        ]
      }
    ]
  },
  "g2-l4": {
    "label": "중2 L4 · so~that & 수동태",
    "color": "#84cc16",
    "questions": [
      {
        "id": "g2_l4_g2_sothat_passive_basic_a1",
        "kor": "그는 너무 피곤해서 움직일 수 없었다.",
        "eng": "He was ___ tired that he couldn't move.",
        "ans": "so",
        "opts": [
          "so",
          "very",
          "too",
          "quite"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a2",
        "kor": "그 영화는 너무 지루해서 우리는 일찍 떠났다.",
        "eng": "The movie was ___ boring that we left early.",
        "ans": "so",
        "opts": [
          "too",
          "very",
          "quite",
          "so"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a3",
        "kor": "그 수프는 너무 뜨거워서 그녀는 먹을 수 없었다.",
        "eng": "The soup was so hot ___ she couldn't eat it.",
        "ans": "that",
        "opts": [
          "when",
          "because",
          "that",
          "which"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a4",
        "kor": "Jake는 너무 빠르게 달려서 아무도 그를 잡을 수 없었다.",
        "eng": "Jake ran so quickly ___ nobody could catch him.",
        "ans": "that",
        "opts": [
          "so",
          "that",
          "when",
          "but"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a5",
        "kor": "가방이 너무 무거워서 Mia는 도움을 요청했다.",
        "eng": "The bag was so heavy ___ Mia asked for help.",
        "ans": "that",
        "opts": [
          "that",
          "because",
          "which",
          "but"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a6",
        "kor": "하늘이 너무 어두워서 우리는 아무것도 볼 수 없었다.",
        "eng": "The sky was so dark ___ we couldn't see anything.",
        "ans": "that",
        "opts": [
          "because",
          "when",
          "but",
          "that"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a7",
        "kor": "음식이 너무 맛있어서 모두가 더 먹고 싶어했다.",
        "eng": "The food was so ___ that everyone wanted more.",
        "ans": "delicious",
        "opts": [
          "delight",
          "deliciousness",
          "delicious",
          "deliciously"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a8",
        "kor": "그녀는 너무 아름답게 노래해서 관중이 박수를 쳤다.",
        "eng": "She sang so ___ that the crowd applauded.",
        "ans": "beautifully",
        "opts": [
          "beautify",
          "beautifully",
          "beautiful",
          "beauty"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a9",
        "kor": "시험이 너무 어려워서 많은 학생들이 떨어졌다.",
        "eng": "The test was so ___ that many students failed.",
        "ans": "difficult",
        "opts": [
          "difficult",
          "difficultly",
          "difficulty",
          "differ"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_a10",
        "kor": "그는 너무 열심히 연습해서 챔피언이 되었다.",
        "eng": "He practiced so ___ that he became the champion.",
        "ans": "hard",
        "opts": [
          "hardly",
          "hardness",
          "harder",
          "hard"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b1",
        "kor": "창문이 어젯밤 누군가에 의해 깨졌다.",
        "eng": "The window ___ by someone last night.",
        "ans": "was broken",
        "opts": [
          "breaks",
          "is breaking",
          "was broken",
          "broken"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b2",
        "kor": "Jake는 한 시간 만에 낡은 자전거를 고쳤다.",
        "eng": "Jake ___ the old bicycle in an hour.",
        "ans": "fixed",
        "opts": [
          "were fixed",
          "fixed",
          "was fixed",
          "is fixed"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b3",
        "kor": "꽃들은 매년 겨울마다 시원한 곳에 보관된다.",
        "eng": "The flowers ___ in a cool place every winter.",
        "ans": "are kept",
        "opts": [
          "are kept",
          "keep",
          "kept",
          "is kept"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b4",
        "kor": "그 오래된 다리는 약 100년 전에 지어졌다.",
        "eng": "The old bridge ___ about a century ago.",
        "ans": "was built",
        "opts": [
          "build",
          "built",
          "is built",
          "was built"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b5",
        "kor": "어제 경기에서 세 골이 득점되었다.",
        "eng": "Three goals ___ scored in the match yesterday.",
        "ans": "were",
        "opts": [
          "was",
          "are",
          "were",
          "is"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b6",
        "kor": "그 편지는 오늘 아침 Yuna가 썼다.",
        "eng": "The letter ___ written by Yuna this morning.",
        "ans": "was",
        "opts": [
          "were",
          "was",
          "are",
          "am"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b7",
        "kor": "많은 책들이 매년 축제에서 판매된다.",
        "eng": "A lot of books ___ sold at the fair every year.",
        "ans": "are",
        "opts": [
          "are",
          "was",
          "is",
          "am"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_basic_b8",
        "kor": "특별한 저녁 식사는 매주 일요일 Jake의 아버지가 요리한다.",
        "eng": "The special dinner ___ cooked by Jake's father on Sundays.",
        "ans": "is",
        "opts": [
          "were",
          "are",
          "am",
          "is"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_hard_a1",
        "kor": "Jake의 방은 너무 지저분해서 그의 엄마가 들어가길 거부했다.",
        "eng": "Jake's room was ___ messy that his mom refused to enter.",
        "ans": "so",
        "opts": [
          "too",
          "quite",
          "so",
          "very"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_hard_a2",
        "kor": "창문들이 지난 토요일 관리팀에 의해 청소되었다.",
        "eng": "The windows ___ cleaned by the maintenance team last Saturday.",
        "ans": "were",
        "opts": [
          "are",
          "were",
          "is",
          "was"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_hard_a3",
        "kor": "Yuna의 발표는 너무 잘 준비되어서 선생님이 그녀에게 추가 점수를 주었다.",
        "eng": "Yuna's speech was so well-prepared ___ her teacher gave her extra credit.",
        "ans": "that",
        "opts": [
          "that",
          "when",
          "because",
          "which"
        ]
      },
      {
        "id": "g2_l4_g2_sothat_passive_hard_a4",
        "kor": "이 특별상은 매년 한 명의 학생에게만 주어진다.",
        "eng": "This special award ___ given to only one student each year.",
        "ans": "is given",
        "opts": [
          "gave",
          "are given",
          "were given",
          "is given"
        ]
      }
    ]
  },
  "all": {
    "label": "전체 랜덤",
    "color": "#64748b",
    "questions": []
  }
};
